medly/medly-components

packages/core/src/components/Table/Body/Row/Row.styled.tsx, packages/core/src/components/Table/Body/Row/__snapshots__/Row.test.tsx.snap, packages/core/src/components/Table/docs/Table.stories.mdx, packages/theme/src/core/table/index.ts, packages/theme/src/core/table/types.ts
ISSUES CLOSED: #157
-   [ ] Bugfix
Added textColor in Table.Row theme
-   [ ] Yes
-   [X] No
=> feat(theme): added textcolor options in table.row theme

packages/core/src/components/Modal/types.ts
-   [x] Bugfix
`Modal.Actions`, `Modal.Content`, and `Modal.Header` aren't defined `WithStyle` in the main `Modal` file where they are declared as static props. This prevents users of the library from …
=> Fix(core): add props and WithStyle type to Modal Header and Content

packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/core/src/components/Table/Table.styled.tsx, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
There’s a hidden div used internally to calculate the length of the column’s largest text to provide
proper column expanding feature. This div was visible on the viewport when the text was longer. In
this fix, we added opacity to the hidden div, so that it is not visible in the viewport.
-   [ ] Bugfix
-   [x] Code style update (formatting, local variables)
- …
=> style(core): added zero opacity to the table’s hidden div

packages/core/src/components/DatePicker/DatePicker.test.tsx, packages/core/src/components/DatePicker/DatePicker.tsx, packages/core/src/components/DatePicker/types.ts, packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
-   [ ] Bugfix
The DatePicker calendar icon currently always displays on desktop
A new `showCalendarIcon` prop has been added to the DatePicker component. It defaults to `true` but can be set to `false` …
=> Add showCalendarIcon to DatePicker

packages/core/src/components/TextField/TextField.tsx
-   [x] Bugfix
Issue was noticed when we tried to add a new autosuggestion feature within noapp to update the form with selected values. The selected values would update the textFields but the textFields …
=> fix(core): textField - setIsTextPresent updates based on value not on onChange of field

packages/core/src/components/DatePicker/DatePicker.stories.mdx, packages/core/src/components/DatePicker/DatePicker.tsx, packages/forms/src/hooks/useForm/useForm.ts, packages/utils/src/helpers/index.ts, packages/utils/src/helpers/isMobile.ts
Removed isMobile from date picker as requested in [PNA-488](https://medlypharmacy.atlassian.net/browse/PNA-488
)
-   [x] Bugfix
On mobile, the native datepicker appears when entering a dob on patient authentication. Desired behavior is …
=> fix: remove isMobile functionality

packages/core/src/components/Tabs/Tab/types.ts, packages/core/src/components/Tabs/Tabs.test.tsx, packages/core/src/components/Tabs/Tabs.tsx, packages/core/src/components/Tabs/types.ts
Added below two prop in `Tabs` component
1. `as` prop to render Tabs as any html tag.
2. `hidePanel` prop to hide the panel section
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
Add any other context or …
=> feat: add as and hidePanel props in Tabs component

packages/core/src/components/TextField/Styled/CharacterCount.styled.tsx, packages/core/src/components/TextField/TextField.test.tsx, packages/core/src/components/TextField/TextField.tsx, packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
-   [ ] Bugfix
Currently, the `characterCount` feature does not change style based on input length:
The `characterCount` now changes to `theme.colors.heartbeat[500]` when the textField input value is …
=> textField characterCount updates

packages/core/src/components/Button/Button.stories.mdx, packages/core/src/components/Button/Button.stories.tsx, packages/core/src/components/Button/Button.test.tsx, packages/core/src/components/Button/__snapshots__/Button.test.tsx.snap, packages/theme/src/core/button/index.ts, packages/theme/src/core/button/types.ts
-   [ ] Bugfix
Buttons have three sizes available: S, M, and L.
Buttons will now have four sizes available: XS, S, M, and L.
The default sizes for S, M, and L have not been altered.
The new XS button follows the spec outlined here: …
=> PES-1463 add 'xs' button size

packages/core/package.json, packages/forms/package.json, packages/icons/package.json, packages/layout/package.json, packages/loaders/package.json, packages/utils/package.json, yarn.lock
-   [x] Bugfix
Currently for projects using react 17 medly components gives warnings.
Added `react 17` also as peer dependency to suppress the warning for projects using react 17.
-   [ ] Yes
-   [x] No
Add any other context or …
=> fix: npm warnings for projects using react 17

packages/core/src/components/Avatar/Avatar.styled.tsx, packages/core/src/components/Avatar/Avatar.test.tsx, packages/core/src/components/Avatar/Avatar.tsx, packages/core/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap, packages/core/src/components/Avatar/types.ts, packages/theme/src/core/avatar/index.ts, packages/theme/src/core/avatar/types.ts
Add pressed state to Avatar component and enable pressed and hover state with onClick prop. Remove
withHoverEffect prop.
BREAKING CHANGE:
withHoverEffect prop was removed.
-   [ ] Bugfix
-   [ ] Other... Please …
=> feat(core): Add pressed state to Avatar component

packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap, packages/core/src/components/SingleSelect/Options/Option/Option.styled.tsx, packages/core/src/components/SingleSelect/SingleSelect.stories.mdx, packages/core/src/components/SingleSelect/SingleSelect.tsx, packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, packages/core/src/components/SingleSelect/types.ts, packages/theme/src/core/singleSelect/index.ts, packages/theme/src/core/singleSelect/types.ts
-   [ ] Bugfix
Currently, the `ChevronDownIcon` is the default suffix/toggle icon for the `SingleSelect` component as it is not customizable. Also, the text color for the `SingleSelect` …
=> feat(core): add and use new single-select props for suffix icon + hovered color

packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap, packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/core/src/components/HelperAndErrorTextTooltip/HelperAndErrorTextTooltip.styled.tsx, packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/core/src/components/SingleSelect/SingleSelect.stories.mdx, packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, packages/core/src/components/TextField/Styled/HelperAndErrorTextTooltipWrapper.styled.tsx, packages/core/src/components/TextField/Styled/InnerWrapper/InnerWrapper.styled.tsx, packages/core/src/components/TextField/Styled/InnerWrapper/fusion.styled.tsx, packages/core/src/components/TextField/Styled/InnerWrapper/outlined.styled.tsx, packages/core/src/components/TextField/Styled/TextField.styled.tsx, packages/core/src/components/TextField/TextField.stories.mdx, packages/core/src/components/TextField/TextField.test.tsx, packages/core/src/components/TextField/TextField.tsx, packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap, packages/theme/src/core/textField/index.ts, packages/theme/src/core/textField/types.ts
-   [x] Bugfix
- Currently the `TextField` component has a set, non-customizable `border-radius` and `border-width` for all variants. 
- Additionally, the existing custom `textColor` for a `TextField` disabled state is not being use
Minor fix …
=> feat(core): textfield custom active border styles

packages/core/src/components/DateRangePicker/DateRangePicker.stories.mdx, packages/core/src/components/DateRangePicker/DateRangePicker.test.tsx, packages/core/src/components/DateRangePicker/DateRangePicker.tsx, packages/core/src/components/DateRangePicker/types.ts
-   [ ] Bugfix
Currently, there is no way to trigger an action, when the user closes the calendar popup after selecting the dates.
#228
a function will be called when the calendar popup closes.
-   [ ] Yes
-   [x] No
Provide any additional …
=> feat: Function to be called after the calendar popup closes

packages/core/src/components/Tabs/TabList/TabList.tsx
-   [x] Bugfix
Currently, the logic to position the slider in the `solid` tabs variant does not properly handle disabled tabs (i.e. if the second tab in the tab list is active and the first tab is disabled, the …
=> fix: fix active tab value for TabList

packages/theme/src/core/font/types.ts, packages/theme/src/core/font/variants.ts
affects: @medly-components/theme
BREAKING CHANGE:
FontVariantTheme type now require h6 variant values also
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: add h6 variant in font variants

packages/core/src/components/Table/Body/Body.tsx, packages/core/src/components/Table/Table.test.tsx, packages/core/src/components/Table/types.ts
-   [ ] Bugfix
To change the text for `noResultRow` you have to create a custom component. The styling for the component needs to be manually adjusted which seems too much work for just changing the text.
Adds `noResultRowText` prop to table …
=> feat(core): add noResutRowText prop in table

packages/core/src/components/Toggle/Toggle.test.tsx, packages/core/src/components/Toggle/Toggle.tsx, packages/core/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap
-   [x] Bugfix
`Toggle` component uses label name as id instead of the id passed
`Toggle` component will use id or label name delimited by `-` (hyphen) else the default id will be `medly-toggle-checkbox`
-   [x] Yes
-   [ ] No
Components …
=> fix: use id in toggle

packages/forms/src/components/Form/Form.test.tsx, packages/forms/src/hooks/useForm/useForm.ts
Allow user to clear number input after entering a number
Once you enter a number in number input, user is now allowed to clear it and there is always a value `0` set
User can clear the number input
=> fix(forms): clear number input

packages/forms/src/hooks/useForm/useForm.ts
Number input should accept zero and allow user to clear the input as well
User cannot add `0` value in number input 😂 
User can add `0` value as well as clear the number input
=> fix(forms): number input accept zero

packages/layout/src/components/SideNav/SideNav.stories.mdx, packages/layout/src/components/SideNav/SideNav.tsx, packages/layout/src/components/SideNav/ToggleSwitch/ToggleSwitch.test.tsx, packages/layout/src/components/SideNav/ToggleSwitch/ToggleSwitch.tsx, packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap, packages/layout/src/components/SideNav/ToggleSwitch/types.ts, packages/layout/src/components/SideNav/types.ts
Adds custom text for sidenav button while expanding or collapsing the sidenav. As per current implementation the text is static and cannot be modified.
Added two test case to handle the state change for `toggleSwitch` component.
[x] should render with custom text passed showing hide option
[x] should render with custom text passed showing open option
As per current implementation the text for expanding or collapsing sidenav is static and cannot be modified.
Adds two props to customize the text as per users requirement
=> feat(layout): add custom expand & collapse text in sidenav

packages/core/src/components/SearchBox/SearchBox.test.tsx, packages/core/src/components/SearchBox/SearchBox.tsx
Persists X in SearchBox after pressing enter.
Matches functionality for pressing enter as when
clicking Search Icon.
Adds 2 tests to confirm both enter and clicking search icon match
functionality.
Fixes [this issue](https://medlypharmacy.atlassian.net/browse/CNCT-1107?atlOrigin=eyJpIjoiZmQ3NzJlZjY0YzIwNGE1MGI5ZjNmOGU2ODljYjkwNDYiLCJwIjoiaiJ9) on behalf of Medly360 team where the SearchBox X disappears after pressing Enter when submitting a non-empty search. Functionality is not broken when submitting a search via the Search Icon.
Created two tests in the Searchbox.test.tsx folder to confirm X does not disappear upon submitting a search with text for both pressing Enter and clicking the Search Icon.
[x] Test A
[x] Test B
You can see a video at the Jira link …
=> fix(core): persists X in SearchBox after pressing enter

packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.stories.mdx, packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.styled.tsx, packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.test.tsx, packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.tsx, packages/core/src/components/CenterAlignedLoader/__snapshots__/CenterAlignedLoader.test.tsx.snap, packages/core/src/components/CenterAlignedLoader/types.ts
Added feature to use the custom message in center align loader component
[ ]  I have written a unit test to check if the custom message is present if you pass the custom message to the component
There is no functionality for passing a custom message to center align loader component 
Now you can pass custom message prop to center align loader component.
=> feat: add custom message support in centerAlignLoader

packages/core/src/components/CardTable/docs/CardTable.stories.mdx, packages/core/src/components/Input/Input.stories.mdx
There was a callout to separate out deprecated components in storybook. This PR moves two components (Input and CardTable) to Deprecated folder in storybook.
Reviewed updates in storybook. See last folder "Deprecated"
[ ] Test A
[ ] Test B
[DS-48](https://medlypharmacy.atlassian.net/jira/software/projects/DS/boards/14/backlog?selectedIssue=DS-48)
Two deprecated components are inside core/ folder in storybook
Two deprecated components are inside deprecated/ folder in storybook
**Note:** No breaking changes
=> docs: move deprecated components to different folder in storybook

packages/core/src/components/Table/helpers.ts
make nested table field resizeable
If field property of column config is using nested/dotted value (user.name) then the column is not resizeable.
Column will be resizeable regardless of using nested value
=> fix(core): make nested table field resizeable

packages/core/src/components/SingleSelect/SingleSelect.tsx
Options dropdown gets blank on the selection of the same option twice, when options are loaded asynchronously.
=> fix(core): fix single select issue for async options

packages/core/src/components/Table/Body/Row/Row.tsx, packages/core/src/components/Table/Table.test.tsx, packages/core/src/components/Table/docs/Table.stories.mdx, packages/core/src/components/Table/types.ts
table > accordion (inside describe)
[x] should render table with accordion
[x] should render table with default expanded row
By default row cannot be expanded
Row expansion can be done by adding `defaultRowExpandKey` and setting the value of key `true`
=> feat(core): add prop to expand row by default

packages/core/src/components/Accordion/Accordion.test.tsx, packages/core/src/components/Accordion/Accordion.tsx, packages/core/src/components/Accordion/Content/Content.styled.tsx, packages/core/src/components/Accordion/types.ts
Remove `max-height: 100vh` from `Accordion.Content` when it is open.
I have updated the unit tests accordingly.
=> fix: accordion content height issue

packages/core/src/components/CssBaseline/fonts.tsx, packages/theme/src/core/font/types.ts
Certain Medly apps use a custom font which has vertical alignment issues on Windows and Android browsers. This change allows users of the library to fine tune the font's vertical spacing.
[x] Manual testing using MacOS and Android devices
Currently we are not exposing the `ascent-override` and `descent-override` properties for a font face.
Added type definitions for `ascent-override` and `descent-override`. These values are now used when generating the global CSS, if they are defined.
=> feat(theme): allow @font-face ascent and descent overrides

packages/core/src/components/Table/Body/Body.tsx, packages/core/src/components/Table/Body/Row/Row.tsx, packages/core/src/components/Table/Body/Row/types.ts, packages/core/src/components/Table/Body/types.ts, packages/core/src/components/Table/Table.test.tsx, packages/core/src/components/Table/Table.tsx, packages/core/src/components/Table/docs/Table.stories.mdx, packages/core/src/components/Table/types.ts
* Adds ability to control the keyboard navigated cursor externally by passing `rowCursor` props. This will allow user to call custom functions while navigating
* Adds `onRowNavigated` prop that accepts a function which will get fired when a row is navigated. It's signature is similar to `onRowClick`
A custom `rowCursor` is passed and it is checked if `onRowNavigated` is called on subsequent re-renders with changed prop values
=> feat: add controlled cursor and onRowNavigated for Table

packages/core/src/components/Modal/Modal.stories.mdx, packages/core/src/components/Modal/Modal.test.tsx, packages/core/src/components/Modal/Modal.tsx, packages/core/src/components/Modal/ModalManager/ModalManager.test.tsx, packages/core/src/components/Modal/ModalManager/ModalManager.ts, packages/core/src/components/Modal/ModalManager/index.ts, packages/core/src/components/Modal/ModalManager/types.ts, packages/core/src/components/Modal/types.ts
* Adds modal manager to manage stacking context of multiple modals which fixes closing of multiple modals on Escape key (#669).
* Adds `disableEscapeKeyDown` prop in case developer wants to disable this behaviour all together and implement their version of Escape key behaviour.
* Multiple modals are added to the document and then their closing behaviour is checked.
* Modal manager is tested by adding and removing of div elements and verifying their indices
Escape key closes all open modals in the document
Escape key only closes the top open modal in the document
=> fix: escape key closes all modal instead of top modal

packages/core/src/components/Table/Body/Cell/RowActionsCell/RowActionsCell.tsx, packages/core/src/components/Table/Body/Row/Row.tsx, packages/core/src/components/Table/Table.test.tsx, packages/core/src/components/Table/constants.ts, packages/core/src/components/Table/docs/Table.stories.mdx, packages/core/src/components/Table/types.ts
Adds support for `selectRow` keybinding to add custom keybinding for selecting a row
This has been manually tested in storybooks by passing the keybinding and testing the selection of row.
A unit test for testing the selection of row has also been added
User is not able to change the default keybinding for selecting a row
User is able to change the default keybinding for selecting a row
**Note:** 
In Table component's keybinding object, `rowClick` has been renamed to `clickRow` to match the naming convention of other variables.
=> feat: add support for keybinding to select row in Table component

packages/core/src/components/Table/Body/Body.test.tsx, packages/core/src/components/Table/Body/Body.tsx, packages/core/src/components/Table/Body/__snapshots__/Body.test.tsx.snap, packages/core/src/components/Table/Table.test.tsx, packages/core/src/components/Table/docs/Table.stories.mdx
fixed the vertical scroll issue on noResultRow prop. The vertical scroll was coming along with the horizontal scroll when we pass noResultRow prop to the table component and there is no data to display.
[ ] Test A
[ ] Test B
(Replace This Text: Please describe any other related information or …
=> fix: Table component noResultRow prop vertical scroll issue

packages/core/src/components/SearchBox/SearchBox.stories.mdx, packages/core/src/components/SearchBox/SearchBox.test.tsx, packages/core/src/components/SearchBox/SearchBox.tsx, packages/core/src/components/SearchBox/types.ts
* Introduction of `isLoading` prop to show loading state of the search
* Adds support for custom loader in search component
Tests have been added which test for loading state
No loading state supported by search component
Introduction of isLoading prop
=> feat: add isLoading and custom loader support in search box

package.json
Add a command to remove symlink created using `yarn link:packages` command
Add a command to automate unlinking of packages
manually
User have to manually navigate to the respected packages and then unlink them
`yarn unlink:packages` will remove all the symlinks for the nested packages
=> chore(packages): add command to remove symlink for packages

packages/core/src/components/FileInput/FileInput.tsx
Removed manual value change using ref on label click.
if the file is already selected, and on file reselection process if we cancel it, it was clearing the file input value, but here the label is not getting cleared. Now if we try to take values from the form submission event, we get the file input value as empty.
[ ] Test A
[ ] Test B
on file reselection process if we cancel it, it's clearing the file input value but not the label. label shows the previously selected file. 
on file reselection process if we cancel it, it will clear the file input value as well as a …
=> PSB | fix(core): remove clearing of value using ref

packages/core/src/components/Modal/Actions/Actions.styled.tsx, packages/core/src/components/Modal/Content/Content.styled.tsx, packages/core/src/components/Modal/Header/Header.styled.tsx, packages/core/src/components/Modal/Header/Header.tsx, packages/core/src/components/Modal/Header/__snapshots__/Header.test.tsx.snap, packages/core/src/components/Modal/Modal.styled.tsx, packages/core/src/components/Modal/Modal.tsx, packages/core/src/components/Modal/Popup/Popup.styled.tsx, packages/core/src/components/Modal/Popup/__snapshots__/Popup.test.tsx.snap, packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap, packages/core/src/components/Modal/useScrollState.ts, packages/utils/src/style/media/media.ts
Update modal styling and fixed some of the bugs related to showing/hiding the shadow for content
overflow as well as header's fixed position on mobile devices.
- Desktop/Tablet: Reduce the outer padding from 48px to 32px.
- Mobile padding has some slight adjustments as well. Refer to Figma for the size differences.
- When scrolling the modal, the top and bottom portions reduce in height according to Figma across all devices.
- There will be 3 default sizes for the modal, but the modal should still be customizable to any width.
Visual updates
Manually
=> feat(core): update modal styling and behavior

packages/core/src/components/Modal/Modal.test.tsx, packages/core/src/components/Modal/Modal.tsx, packages/core/src/components/Modal/Popup/Popup.tsx
Reverts a stopPropagation from Popup component that was removed earlier
This has been tested manually and a test has also been added to verify the same
When `shouldClickOnOutsideClick` is passed, the modal closes even on clicking on the modal
When `shouldClickOnOutsideClick` is passed, the modal does not close on clicking on the modal
=> fix: should not close modal on clicking on modal 

packages/core/src/components/Modal/Modal.tsx, packages/core/src/components/Modal/Popup/Popup.tsx
ISSUES CLOSED: #688
Handles the issue of modal being closed on click on outside of modal and also the issue of closing the singleSelect on clicking on outside of single select component.
On Clicking outside of any SingleSelect component which is being used in Modal is not closing the dropdown.
Now Clicking outside of any SingleSelect component which is being used in Modal is closing the dropdown.
=> fix: modal close issue on click on outside of modal

packages/core/src/components/DatePicker/DatePicker.tsx
The issues is easy to replicate when you hydrate a from with a \`null\` value prop for the
`DatePicker`,notice how the text keeps the old value.
The component `DatePicker` is when getting the prop value set to `null`, due to boolean evaluation of the following expresion
```
date && setTextValue(format(date, displayFormat).replace(new RegExp('\\/|\\-', 'g'), ' $& '));
```
Will not execute the `setTextValue` function, keeping the old value for the `TextField`.
Example
t1. <Datepicker value ='01/01/2022`>  --> on screen 01/01/2022
t2 <Datepicker value ={null}>  --> on screen 01/01/2022
https://user-images.githubusercontent.com/101274033/179564709-02a19abf-9db4-4e91-92fc-1a6e86a0c22f.mov
More details in here
https://medlypharmacy.atlassian.net/browse/CHILL-707 …
=> fix(core): DatePicker is not reseting the text field value when the `prop` value is `null`

packages/core/src/components/Modal/Header/Header.styled.tsx, packages/core/src/components/Modal/Header/__snapshots__/Header.test.tsx.snap, packages/core/src/components/Modal/Modal.tsx, packages/core/src/components/Modal/Popup/Popup.styled.tsx, packages/core/src/components/Modal/Popup/__snapshots__/Popup.test.tsx.snap, packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap
Updated core modal border radius and padding to avoid overlap of title and close button.
There was a mix of values for border radius, some places using `1.6rem` and others `1.2rem` and we decided 1.2 is the correct value.
I attached screenshots for the header's padding values, we're now making sure that the close button won't overlap the text.
Before
After
=> feat(core): updated core modal border radius and padding

packages/core/src/components/SearchBox/SearchBox.test.tsx, packages/core/src/components/SearchBox/SearchBox.tsx
If user provided initial value to the component then it should render close icon.
[ ] Test A
[ ] Test B
=> fix(core): fix close icon bug, when initial value is provided.

packages/core/src/components/Drawer/Drawer.styled.tsx, packages/core/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap, packages/layout/src/components/Header/Nav/Nav.styled.tsx, packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap, packages/layout/src/components/SidePanel/SidePanel.styled.tsx, packages/layout/src/components/SidePanel/__snapshots__/SidePanel.test.tsx.snap
affects: @medly-components/core, @medly-components/layout
Fixes the issue that causes transparent sidenav in Header component.
This is a revert of https://github.com/medly/medly-components//commit/eea5e621534f1eb88cca2e1eb0ab66e447a9e40d after the new webkit browser update
[ ] Test A
[ ] Test B …
=> revert: sidenav and drawer height issue on mobile devices

packages/core/src/components/Breadcrumb/Back/Back.styled.tsx, packages/core/src/components/Breadcrumb/Back/Back.tsx, packages/core/src/components/Breadcrumb/Breadcrumb.stories.mdx, packages/core/src/components/Breadcrumb/Breadcrumb.tsx, packages/core/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap, packages/core/src/components/Breadcrumb/types.ts
Add Style property to Breadcrumb Back component and make the icon size `M` as per the design.
There is no `Style` property available for BreadcrumbBack component, and the icon size was also not correct as per the design.
T`Style` property is now available for BreadcrumbBack component, and the icon size is `M` as per the design.
=> feat: add Style property to Breadcrumb Back component

packages/layout/src/components/SideNav/MedlySidenavHeader/MedlySidenavHeader.test.tsx, packages/layout/src/components/SideNav/MedlySidenavHeader/MedlySidenavHeader.tsx, packages/layout/src/components/SideNav/MedlySidenavHeader/types.ts
use `Logo` prop types for `MedlySidenavHeader` prop types
The types are different for `MedlySidenavHeader` which is eventually being passed to the `Logo` component
use `Logo` prop types for `MedlySidenavHeader` prop types
=> refactor: use `Logo` prop types for `MedlySidenavHeader` prop types

package.json, packages/core/src/components/Tabs/Tab/Tab.styled.tsx, packages/core/src/components/Tabs/Tab/__snapshots__/Tab.test.tsx.snap, packages/core/src/components/Tabs/Tab/types.ts, packages/core/src/components/Tabs/TabList/TabList.tsx, packages/core/src/components/Tabs/TabList/__snapshots__/TabList.test.tsx.snap, packages/core/src/components/Tabs/TabList/types.ts, packages/core/src/components/Tabs/TabPanel/TabPanel.styled.tsx, packages/core/src/components/Tabs/TabPanel/__snapshots__/TabPanel.test.tsx.snap, packages/core/src/components/Tabs/Tabs.stories.mdx, packages/core/src/components/Tabs/Tabs.test.tsx, packages/core/src/components/Tabs/Tabs.tsx, packages/core/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap, packages/core/src/components/Tabs/types.ts, yarn.lock
Add `fullWidth`  prop to `Tabs` component so that TabList can take parents full width
There is no way to make TabsList full width
After passing `fullWidth`  prop to `Tabs` component `TabList` will take parents full width
=> feat: add fullWidth feature in Tabs component

packages/core/src/components/Accordion/Content/Content.styled.tsx
Set overflow visible to `Accordion.Content` component when accordion is visible so that if that renders any popup that can be visible
[ ] Test A
[ ] Test B
`Accordion.Content` is by default overflow hidden and because of that any pop up like datepicker is not visible
Overflow is set to visible for `Accordion.Content` component when accordion is visible so that any pop up inside the content can be visible
(Replace This Text: …
=> fix: set overflow visible when accordion is visible

packages/core/src/components/Drawer/Drawer.tsx, packages/core/src/components/Drawer/types.ts
Any popup like `Calendar` or `SingleSelct` popup is not closing on clicking outside of popup but inside `Drawer` component. Because the eventPropagation was stopped in `Drawer` component and beacuse of that those popup are not closing.
[ ] Test A
[ ] Test B
Any popup like `Calendar` or `SingleSelct` popup is not closing on clicking outside of popup but inside `Drawer` component. 
Now popup like `Calendar` or `SingleSelct` popup is closing on clicking outside of popup but inside `Drawer` component. 
**Note:** (Replace This Text: If this PR contains a breaking change …
=> fix: fix closing any popup like calendar in drawer component

packages/core/src/components/MultiSelect/MultiSelect.tsx, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
Stop passing `placeholder` prop to `Wrapper` component in `MultiSelect` component.
[ ] Test A
[ ] Test B
Placeholder prop is by mistakenly passed to Wrapper component.
Placeholder prop is now not being passed to Wrapper component.
=> fix: stop passing placeholder to wrapper component in multiselect component

packages/core/src/components/DatePicker/DatePicker.stories.mdx, packages/core/src/components/DatePicker/DatePicker.styled.tsx, packages/core/src/components/DatePicker/DatePicker.test.tsx, packages/core/src/components/DatePicker/DatePicker.tsx, packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap, packages/core/src/components/DatePicker/types.ts
Add an option to hide input in datepicker component via passing the prop `hideInput`. This feature will help us to render the datepicker like below 
Added the unit to test the component with `hideInput` prop being passed.
=> feat: add an option to hide input in datepicker component

packages/core/src/components/SingleSelect/SingleSelect.tsx
ISSUES CLOSED: #718
This PR resolves the focus issue on a single select field which is mentioned in the #718 issue ticket.
[ ] Test A
[ ] Test B
the focus was not getting removed on the outside click, it was opening an options popup when we press the down arrow key
Removed focus on the outside click, It will not open the option popup when we click outside and press the down arrow key.
(Replace This Text: Please describe any other …
=> fix(core): fixed single select outside click focus issue

packages/core/src/components/SearchBox/SearchBox.test.tsx, packages/core/src/components/SearchBox/SearchBox.tsx
ISSUES CLOSED: #725
fixed the SearchBox search trigger issue on option selection using the up-down arrow keys and enter key press.
[ ] Test A
[ ] Test B
when we select an option using the up-down arrow keys and press enter, it triggers the search event again.
when we select an option using the up-down arrow keys and press enter, it will not trigger the search event.
=> feat(core): fixed SearchBox search trigger issue on option selection using enter

packages/core/src/components/SingleSelect/SingleSelect.test.tsx, packages/core/src/components/SingleSelect/SingleSelect.tsx
ISSUES CLOSED: #728
triggering blur event not removing the Single Select focus, still able to open the drop-down using down arrow key.
[ ] Test A
[ ] Test B
able open drop-down using the down arrow key after the blur event triggered using ref
will remove the focus on the blur event, and will not open dropdown.
=> fix(core): on blur event not removing focus properly able to open drop down using arrow key

packages/core/src/components/TimePicker/TimePicker.stories.mdx, packages/core/src/components/TimePicker/TimePicker.stories.tsx, packages/core/src/components/TimePicker/TimePicker.styled.tsx, packages/core/src/components/TimePicker/TimePicker.test.tsx, packages/core/src/components/TimePicker/TimePicker.tsx, packages/core/src/components/TimePicker/TimePickerPopup/TimePickerPopup.styled.tsx, packages/core/src/components/TimePicker/TimePickerPopup/TimePickerPopup.tsx, packages/core/src/components/TimePicker/TimePickerPopup/index.ts, packages/core/src/components/TimePicker/TimePickerPopup/types.ts, packages/core/src/components/TimePicker/__snapshots__/TimePicker.test.tsx.snap, packages/core/src/components/TimePicker/types.ts, packages/theme/src/core/index.ts, packages/theme/src/core/timePicker/index.ts, packages/theme/src/core/timePicker/types.ts, packages/theme/src/core/types.ts, packages/theme/src/types.ts
The `TimePicker` is a controlled component that allows you to select a time through input text or using a dialog. This component will return the time in **24-hour format**. This component will use the native dialog on the mobile devices.
Added unit test cases
=> feat: add new TimePicker component

packages/core/src/components/TextField/Styled/MaskPlaceholder.styled.tsx, packages/core/src/components/TextField/TextField.tsx, packages/core/src/components/TextField/getMaskedValue.test.ts, packages/core/src/components/TextField/getMaskedValue.ts, packages/core/src/components/TimePicker/TimeOptionList/TimeOptionList.styled.tsx, packages/core/src/components/TimePicker/TimeOptionList/TimeOptionList.tsx, packages/core/src/components/TimePicker/TimeOptionList/index.ts, packages/core/src/components/TimePicker/TimeOptionList/types.ts, packages/core/src/components/TimePicker/TimePicker.styled.tsx, packages/core/src/components/TimePicker/TimePicker.test.tsx, packages/core/src/components/TimePicker/TimePicker.tsx, packages/core/src/components/TimePicker/TimePickerPopup/TimePickerPopup.styled.tsx, packages/core/src/components/TimePicker/TimePickerPopup/TimePickerPopup.tsx, packages/core/src/components/TimePicker/TimePickerPopup/types.ts, packages/core/src/components/TimePicker/TimePickerTextField/TimePickerTextField.tsx, packages/core/src/components/TimePicker/TimePickerTextField/types.ts, packages/core/src/components/TimePicker/__snapshots__/TimePicker.test.tsx.snap, packages/forms/src/components/Fields/Fields.components.tsx, packages/forms/src/components/Form/Form.test.tsx, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap, packages/theme/src/core/timePicker/index.ts, packages/theme/src/core/timePicker/types.ts
=> feat: update timepicker styles
