medly/medly-components

packages/core/package.json, yarn.lock
https://github.com/tresko/react-datepicker/issues/39
=> fix(core): upgrade datepicker-react/styled package version

packages/core/src/components/Table/Cell/Cell.styled.tsx, packages/core/src/components/Table/Cell/Cell.tsx, packages/core/src/components/Table/Cell/types.ts, yarn.lock
Clicking on cell for a table with checkbox was opening history modal. Also hovering on the same cell outside checkbox was showing cursor as pointer. Fixed those issues as part of this PR.
=> Fixed clicking on the cell with checkbox opening modal

packages/core/src/components/CardTable/Body/Body.test.tsx, packages/core/src/components/CardTable/Body/Body.tsx, packages/core/src/components/CardTable/Body/Row/Row.styled.tsx, packages/core/src/components/CardTable/Body/__snapshots__/Body.test.tsx.snap, packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap, packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
-   [ ] Bugfix
-   [ ] Application / infrastructure changes
Issue Number: N/A
-   [ ] Yes
-   [ ] No
=> feat(core): add no result row to cards table

packages/core/src/components/Accordion/Accordion.stories.mdx, packages/core/src/components/Accordion/Accordion.stories.tsx, packages/core/src/components/Accordion/Accordion.styled.tsx, packages/core/src/components/Accordion/Accordion.test.tsx, packages/core/src/components/Accordion/Accordion.tsx, packages/core/src/components/Accordion/__snapshots__/Accordion.test.tsx.snap, packages/core/src/components/Accordion/index.ts, packages/core/src/components/Accordion/types.ts, packages/theme/src/core/accordion/index.ts, packages/theme/src/core/accordion/types.ts, packages/theme/src/core/index.ts, packages/theme/src/core/types.ts, packages/theme/src/types.ts
-   [ ] Bugfix
-   [ ] Application / infrastructure changes
Issue Number: N/A
-   [ ] Yes
-   [x] No
=> feat(core): add accordion component

.github/workflows/release.yml, .releaserc, .stylelintignore, README.md, docs/Introduction.stories.mdx, package.json, yarn.lock
-   [ ] Bugfix
-   [ ] Application / infrastructure changes
We have to manually publish the packages.
Issue Number: N/A
Packages will be published automatically on pull request merged to master.
-   [ ] Yes
-   [x] No
=> feat: add semantic release

packages/forms/src/components/Form/Form.stories.mdx
Fix form import typo in documentation.
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> fix: form import doc

packages/core/src/components/CardTable/Body/Row/Row.styled.tsx, packages/core/src/components/CardTable/Body/Row/Row.test.tsx, packages/core/src/components/CardTable/Body/Row/__snapshots__/Row.test.tsx.snap, packages/core/src/components/CardTable/docs/CardTable.stories.tsx, packages/theme/src/core/cardTable/index.ts, packages/theme/src/core/cardTable/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> Added Row Disabled Bg Color for Card Table

packages/core/src/components/Avatar/Avatar.test.tsx, packages/core/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
Hover Related Code was not getting covered after default value for Hover was reversed
-   [ ] Bugfix
-   [x] Adding missing tests
-   [ ] Yes
-   [x] No
=> Test(core): Elevated Test coverage for Avatar

packages/core/src/components/SearchBox/SearchBox.test.tsx, packages/core/src/components/SearchBox/SearchBox.tsx, packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
-   [ ] Bugfix
-   [x] Other... Please describe: Tests for searchBox
-   [ ] Yes
-   [x] No
=> fix: add more tests for searchBox

packages/core/src/components/CardTable/Body/Body.tsx, packages/core/src/components/CardTable/Body/Cell/Cell.test.tsx, packages/core/src/components/CardTable/Body/Cell/Cell.tsx, packages/core/src/components/CardTable/Body/Cell/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: add rowData as props to cells in CardTable.

packages/core/src/components/CardTable/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> Add rowData to  custom component types

packages/core/src/components/MultiSelect/Chip/index.ts, packages/core/src/components/MultiSelect/InputSuffix/InputSuffix.styled.tsx, packages/core/src/components/MultiSelect/InputSuffix/InputSuffix.tsx, packages/core/src/components/MultiSelect/InputSuffix/index.ts, packages/core/src/components/MultiSelect/InputSuffix/types.ts, packages/core/src/components/MultiSelect/MultiSelect.stories.mdx, packages/core/src/components/MultiSelect/MultiSelect.stories.tsx, packages/core/src/components/MultiSelect/MultiSelect.styled.tsx, packages/core/src/components/MultiSelect/MultiSelect.test.tsx, packages/core/src/components/MultiSelect/MultiSelect.tsx, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/core/src/components/MultiSelect/types.ts, packages/core/src/components/TextField/types.ts, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> Multiselect validation

packages/core/src/components/Table/Head/Head.tsx, packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx, packages/core/src/components/Table/Head/HeadCell/HeadCell.tsx
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> Fixed Table Header Alignment according to TableColumnConfig

packages/core/src/components/Table/Head/HeadCell/HeadCell.tsx, packages/core/src/components/Table/Table.tsx
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> Fix: Corrected Logic to Pick defaultSortOrder when old sortState is none

packages/core/src/components/Table/Head/HeadCell/HeadCell.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> Fix: Removed use of none from HeadCell Sort

packages/core/src/components/Table/useRowSelector.ts
affects: @medly-components/core, @medly-components/forms, @medly-components/layout
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix toggle selection caching issue

packages/core/src/components/Table/Body/Row/Row.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix table onRowSelection context caching issue

packages/forms/src/components/Fields/Fields.components.tsx, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> Fixed nested type form error message

packages/core/src/components/Pagination/Pagination.stories.mdx, packages/core/src/components/Pagination/Pagination.stories.tsx, packages/core/src/components/Pagination/Pagination.styled.tsx, packages/core/src/components/Pagination/Pagination.test.tsx, packages/core/src/components/Pagination/Pagination.tsx, packages/core/src/components/Pagination/PaginationPopup/PaginationPopup.styled.tsx, packages/core/src/components/Pagination/PaginationPopup/PaginationPopup.test.tsx, packages/core/src/components/Pagination/PaginationPopup/PaginationPopup.tsx, packages/core/src/components/Pagination/PaginationPopup/__snapshots__/PaginationPopup.test.tsx.snap, packages/core/src/components/Pagination/PaginationPopup/index.ts, packages/core/src/components/Pagination/PaginationPopup/types.ts, packages/core/src/components/Pagination/__snapshots__/Pagination.test.tsx.snap, packages/core/src/components/Pagination/helper.test.ts, packages/core/src/components/Pagination/helper.ts, packages/core/src/components/Pagination/types.ts, packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap, packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap, packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap, packages/theme/src/core/index.ts, packages/theme/src/core/pagination/index.ts, packages/theme/src/core/pagination/types.ts, packages/theme/src/core/types.ts, packages/theme/src/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat(core): update pagination component as per new design

packages/core/src/components/Table/Body/Cell/Cell.test.tsx, packages/core/src/components/Table/Body/Cell/Cell.tsx, packages/core/src/components/Table/Body/Cell/__snapshots__/Cell.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> Fix/ Show tooltip on hover of ellipses

packages/core/src/components/Table/ActionBar/ActionBar.styled.tsx, packages/core/src/components/Table/ActionBar/ActionBar.test.tsx, packages/core/src/components/Table/ActionBar/ActionBar.tsx, packages/core/src/components/Table/ActionBar/__snapshots__/ActionBar.test.tsx.snap, packages/core/src/components/Table/ActionBar/index.ts, packages/core/src/components/Table/Table.tsx, packages/core/src/components/Table/docs/Table.stories.mdx, packages/core/src/components/Table/docs/Table.stories.tsx, packages/core/src/components/Table/types.ts, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap, packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap, packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap, packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap, packages/theme/src/core/table/index.ts, packages/theme/src/core/table/types.ts
affects: @medly-components/core, @medly-components/forms, @medly-components/theme
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat(core): add action bar component

packages/core/src/components/SingleSelect/SingleSelect.test.tsx, packages/core/src/components/SingleSelect/SingleSelect.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix single select option selection issue

packages/core/src/components/MultiSelect/Options/Options.styled.ts, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix multiselect options overlay z-index issue

packages/core/src/components/Table/types.ts
-   [x] Bugfix
-   [ ] Yes
-   [ ] No
=> Fix: Prop Type for groupBy in Table component

packages/core/src/components/DatePicker/DatePicker.tsx
…definition
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): add missing dependency in datepicker text change callback definition

packages/core/src/components/Table/Body/Cell/Cell.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat: Added formatter support for custom component in table row

packages/core/src/components/TextField/Styled/TextField.styled.tsx, packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
-   [ ] Bugfix
-   [x] Other... Please describe: **Update label placement for fusion variant only**
Fusion variant label is 2px too far to the right
PNA-112
-   [ ] Yes
-   [x] No
Jira ticket: …
=> Text field - micro change to fusion label placement 

packages/core/src/components/Table/Body/Cell/ExtendedRowCell/ExtendedRowCell.tsx
Lazy load expanded row
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> lazy load expanded rows

packages/core/src/components/Table/Body/Cell/types.ts, packages/core/src/components/Table/Body/Row/Row.tsx, packages/core/src/components/Table/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix: type issue in the Cell component

packages/core/src/components/TextField/Styled/TextField.styled.tsx, packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap
-   [ ] Bugfix
-   [x] Other... Please describe: Update font weight for label when input is focused
-   [ ] Yes
-   [x] No
=> Change fusion label weight

packages/core/src/components/Calendar/Calendar.styled.tsx, packages/core/src/components/Calendar/Calendar.tsx, packages/core/src/components/DateRangePicker/DateRangeCalendar/Month/Month.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix: minSelectable date issue in DatePicker & DateRangePicker component

packages/core/src/components/Table/Body/Cell/Cell.tsx, packages/core/src/components/Table/Body/Cell/types.ts, packages/core/src/components/Table/Body/Row/Row.tsx, packages/core/src/components/Table/Table.styled.tsx, packages/core/src/components/Table/Table.tsx, packages/core/src/components/Table/TableProps.context.tsx, packages/core/src/components/Table/docs/columns.tsx, packages/core/src/components/Table/docs/data.ts, packages/core/src/components/Table/types.ts, packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap, packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap, packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [ ] No
=> fix: fit content issue in Table component and pass rowData in formatter function

packages/core/src/components/Modal/Modal.test.tsx, packages/core/src/components/Modal/Modal.tsx
-   [x] Bugfix
-   [ ] Yes
-   [ ] No
=> fix: modal background scroll issue

packages/core/src/components/MultiSelect/Options/Chip/Chip.test.tsx, packages/core/src/components/MultiSelect/Options/Chip/Chip.tsx, packages/core/src/components/MultiSelect/Options/Chip/types.ts, packages/core/src/components/MultiSelect/Options/Options.tsx, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix(core): using label instead of value to display chip in multiselect filter

packages/core/src/components/index.ts, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap, packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap, packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap, packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
-   [x] Bugfix
Dialogbox is not exported to be used in another app
Dialog is exported as default to be used in other apps
-   [ ] Yes
-   [x] No
Add any other context or screenshots about the feature pr …
=> DialogBox: expose dialogbox in components/index.ts

packages/core/src/components/Table/Foot/Foot.tsx, packages/core/src/components/Table/Table.test.tsx
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix(core): display correct total items if they are less than items per page

packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/core/src/components/Table/Body/Body.tsx, packages/core/src/components/Table/Foot/Foot.tsx, packages/core/src/components/Table/Table.test.tsx, packages/core/src/components/Table/docs/Table.stories.mdx, packages/core/src/components/Table/types.ts
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> Added NoResultRow Component and Fixed Range Display in Table Footer Pagination

packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/core/src/components/Table/Body/Cell/Styled/CustomComponentWrapper.styled.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix table custom cell alignment issue

packages/core/src/components/Chip/Chip.styled.tsx, packages/core/src/components/Chip/__snapshots__/Chip.test.tsx.snap, packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> Added font-family inheritance in Chips component

packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/core/src/components/Table/Body/GroupedRow/GroupedRow.tsx, packages/core/src/components/Table/docs/Table.stories.mdx, packages/core/src/components/Table/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: default row expansion in grouped table

packages/core/package.json, packages/core/src/components/DatePicker/DatePicker.test.tsx, packages/core/src/components/DatePicker/DatePicker.tsx, packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/utils/package.json, packages/utils/src/helpers/parseToDate.ts
affects: @medly-components/core, @medly-components/utils
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: invalid date if month is greater then 12

packages/core/src/components/Table/Foot/Foot.tsx, packages/core/src/components/Table/Table.test.tsx
-   [x] Bugfix
-   [ ] Yes
-   [ ] No
=> fix: last page of pagination shows incorrect range

.storybook/main.js, packages/core/src/components/Card/Card.styled.tsx, packages/core/src/components/Card/__snapshots__/Card.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: padding issue in card component

.github/workflows/release.yml
-   [ ] Bugfix
-   [x] CI related changes
-   [ ] Yes
-   [x] No
=> fix: change default branch name

packages/core/src/components/Table/Head/types.ts, packages/core/src/components/Table/Table.tsx, packages/core/src/components/Table/helpers.ts, packages/core/src/components/Table/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix column width size issue on hide/show column from column configuration

packages/core/src/components/Modal/Modal.styled.tsx, packages/core/src/components/Modal/Popup/Popup.styled.tsx, packages/core/src/components/Modal/Popup/__snapshots__/Popup.test.tsx.snap, packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: add animation in modal desktop version

packages/core/src/components/Table/GroupCell/GroupCell.styled.tsx, packages/core/src/components/Table/GroupCell/__snapshots__/GroupCell.test.tsx.snap, packages/core/src/components/Table/Head/HeadRow/HeadRow.styled.tsx, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
-   [X] Tests for the changes have been added (for bug fixes / features)
-   [X] Bugfix
-   [ ] Yes
-   [x] No
=> fix(core): fix column separator is getting hidden on hide/show column

packages/core/src/components/Modal/useScrollState.ts, packages/core/src/components/Table/Body/Body.tsx, packages/core/src/components/Table/Minimap/Minimap.styled.tsx, packages/core/src/components/Table/Minimap/Minimap.test.tsx, packages/core/src/components/Table/Minimap/Minimap.tsx, packages/core/src/components/Table/Minimap/__snapshots__/Minimap.test.tsx.snap, packages/core/src/components/Table/Minimap/types.ts
-   [X] Bugfix
fix minimap styling changes, add minimap dimension dependencies prop and allow modal scroll event to propagate
-   [ ] Yes
-   [X] No
Add any other context or screenshots about the feature …
=> fix(core): fix minimap styling, add dimension dependencies and modal scroll event propagation

packages/core/src/components/ToastContainer/ToastContainer.styled.tsx, packages/core/src/components/ToastContainer/__snapshots__/ToastContainer.test.tsx.snap
-   [X] Tests for the changes have been added (for bug fixes / features)
updates the z-index of toaster component such that it is greater than modal component
-   [ ] Bugfix
-   [ ] Yes
-   [X] No
=> fix(core): update z-index of toaster component

packages/core/src/components/Table/Body/Row/Row.tsx
-   [x] Bugfix
-   [ ] Yes
-   [ ] No
=> fix: row hover action visibility on table when it is loading

packages/core/src/components/Table/Table.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> refactor: add default values of Table props

lerna.json, packages/core/src/components/Table/Body/Body.tsx, packages/core/src/components/Table/Body/Row/Row.styled.tsx, packages/core/src/components/Table/Body/Row/Row.test.tsx, packages/core/src/components/Table/Body/Row/__snapshots__/Row.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix(core): fix minimap positioning issue when no results are present in table

packages/utils/src/helpers/isMobile.ts
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: navigator undefined issue

packages/core/src/components/SingleSelect/Options/Option/Option.tsx, packages/core/src/components/SingleSelect/SingleSelect.test.tsx
-   [x] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix null being treated as custom component

packages/core/src/components/Table/Minimap/Minimap.styled.tsx, packages/core/src/components/Table/Minimap/Minimap.tsx, packages/core/src/components/Table/Minimap/__snapshots__/Minimap.test.tsx.snap
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix minimap positioning issue on table column resize, table resize

packages/core/package.json, packages/core/src/components/Table/Minimap/Minimap.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix minimap resize and controller positioning issue on table resize

packages/core/src/components/Table/Foot/Foot.styled.tsx, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix(core): fix table footer style to keep it visible on table vertical scroll

babel.config.js, packages/core/src/components/Button/Loader/Loader.svg, packages/core/src/components/Button/__snapshots__/Button.test.tsx.snap, packages/core/src/components/CenterAlignedLoader/__snapshots__/CenterAlignedLoader.test.tsx.snap, packages/core/src/types.ts, packages/layout/src/components/SideNav/MedlySidenavHeader/__snapshots__/MedlySidenavHeader.test.tsx.snap, yarn.lock
affects: @medly-components/core, @medly-components/layout
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: button loader visibility issue

packages/core/src/components/MultiSelect/Options/Chip/Chip.styled.ts, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: button type issue in multiselect chip component

packages/core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap, packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap, packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, packages/core/src/components/Table/ActionBar/__snapshots__/ActionBar.test.tsx.snap, packages/core/src/components/TextField/Styled/CharacterCount.styled.tsx, packages/core/src/components/TextField/Styled/InnerWrapper/InnerWrapper.styled.tsx, packages/core/src/components/TextField/Styled/TextField.styled.tsx, packages/core/src/components/TextField/Styled/index.ts, packages/core/src/components/TextField/TextField.stories.mdx, packages/core/src/components/TextField/TextField.test.tsx, packages/core/src/components/TextField/TextField.tsx, packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/core/src/components/TextField/types.ts, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap, packages/layout/src/components/SideNav/NavItem/__snapshots__/NavItem.test.tsx.snap, packages/layout/src/components/SideNav/ToggleSwitch/__snapshots__/ToggleSwitch.test.tsx.snap, packages/layout/src/components/SideNav/__snapshots__/SideNav.test.tsx.snap
-   [ ] Bugfix
`characterCount` prop has been added to the `TextField` component which will show the current character count of the input value when a `maxLength` prop is also passed. 
-   [ ] Yes
-   [x] …
=> feat(core): add characterCount to TextField component

packages/core/src/components/SearchBox/SearchBox.tsx
Pass className prop to wrapper in `Searchbox` component
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat: pass className prop to wrapper in Searchbox component

packages/core/src/components/Avatar/Avatar.styled.tsx, packages/core/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap
-   [x] Bugfix
On mobile devices the width of the avatar decreases.
Avatar size will remain as it is on mobile devices aswell
-   [ ] Yes
-   [ ] No
Add any other context or screenshots about the feature …
=> fix: fix width issue in avatar component

package.json, packages/core/package.json, packages/forms/package.json, packages/icons/package.json, packages/layout/package.json, packages/loaders/package.json, packages/utils/package.json
affects: @medly-components/core, @medly-components/forms, @medly-components/icons,
@medly-components/layout, @medly-components/loaders, @medly-components/utils
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
Add any other context or screenshots …
=> feat: add react 17 also as peer dependency

packages/core/src/components/MultiSelect/MultiSelect.stories.tsx, packages/core/src/components/MultiSelect/MultiSelect.tsx, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/core/src/components/MultiSelect/helpers.ts, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
-   [x] Bugfix
The `Multiselect` component currently displays the `value` of selected options in the text field.
#287
The `Multiselect` component has been updated to display the `label` of selected …
=> fix(core): update multiselect to display option label

packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap, packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/core/src/components/Modal/Modal.stories.tsx, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, packages/core/src/components/TextField/Styled/Label.styled.tsx, packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> Fixes label overflow issue in textfield label

packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.styled.tsx, packages/core/src/components/CenterAlignedLoader/__snapshots__/CenterAlignedLoader.test.tsx.snap, packages/core/src/components/DatePicker/DatePicker.styled.tsx, packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap, packages/core/src/components/DateRangePicker/DateRangeCalendar/DateRangeCalendar.styled.tsx, packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/core/src/components/Drawer/Drawer.styled.tsx, packages/core/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap, packages/core/src/components/MultiSelect/Options/Options.styled.ts, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/core/src/components/Pagination/PaginationPopup/PaginationPopup.styled.tsx, packages/core/src/components/Popover/Popup/__snapshots__/Popup.test.tsx.snap, packages/core/src/components/Popover/Popup/styled/Popup.styled.tsx, packages/core/src/components/Popover/Popup/styled/WithArrow.tsx, packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap, packages/core/src/components/SingleSelect/Options/Options.styled.tsx, packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, packages/core/src/components/Table/ActionBar/__snapshots__/ActionBar.test.tsx.snap, packages/core/src/components/Table/Minimap/Minimap.styled.tsx, packages/core/src/components/Table/Minimap/__snapshots__/Minimap.test.tsx.snap, packages/core/src/components/TextField/Styled/CharacterCount.styled.tsx, packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap, packages/utils/src/helpers/debounce.ts
-   [x] Bugfix
-   [x] Code style update (formatting, local variables)
-   [ ] Yes
-   [x] No
=> fix(core, forms): updates the z-index values of components

packages/core/src/components/Calendar/__snapshots__/Calendar.test.tsx.snap, packages/core/src/components/DatePicker/DatePicker.stories.mdx, packages/core/src/components/DatePicker/DatePicker.tsx, packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap, packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/core/src/components/MultiSelect/MultiSelect.stories.mdx, packages/core/src/components/MultiSelect/MultiSelect.styled.tsx, packages/core/src/components/MultiSelect/MultiSelect.test.tsx, packages/core/src/components/MultiSelect/MultiSelect.tsx, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/core/src/components/MultiSelect/types.ts, packages/core/src/components/SingleSelect/SingleSelect.stories.mdx, packages/core/src/components/SingleSelect/SingleSelect.styled.tsx, packages/core/src/components/SingleSelect/SingleSelect.tsx, packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, packages/forms/src/components/Fields/Fields.components.tsx, packages/forms/src/components/Form/Form.styled.tsx, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
-   [x] Bugfix
There was inconsistence behaviour for min width in all the form fields.
All the form fields now accept the `minWidth` prop.
-   [ ] Yes
-   [x] No
=> Fix min width issue in all the form fields

packages/core/src/components/Table/docs/Table.stories.mdx
Please check if your PR fulfils the following requirements:
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> doc(core): added documentation for custom table cell component

package.json
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> refactor: remove yarn.lock as well in clean command

packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap, packages/core/src/components/Table/docs/Table.stories.mdx, packages/core/src/components/Table/docs/Table.stories.tsx, packages/core/src/components/Table/docs/data.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> SW | docs(core): adds table features list with easy navigation

packages/core/src/components/Table/docs/Table.stories.mdx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> SW | docs(core): updates documentation of row selection

packages/core/src/components/Table/Body/Cell/ExtendedRowCell/ExtendedRowCell.styled.tsx, packages/core/src/components/Table/Body/Cell/RowActionsCell/RowActionsCell.styled.tsx, packages/core/src/components/Table/Body/Cell/RowActionsCell/RowActionsCell.tsx, packages/core/src/components/Table/Body/Cell/Styled/Cell.styled.tsx, packages/core/src/components/Table/Foot/Foot.styled.tsx, packages/core/src/components/Table/Foot/Foot.tsx, packages/core/src/components/Table/Head/Head.tsx, packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap, packages/core/src/components/Table/docs/Table.stories.mdx, packages/core/src/components/Table/helpers.ts, packages/core/src/components/Table/types.ts
-   [X] Tests for the changes have been added (for bug fixes / features)
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat(core): introduce XS size in table component

packages/core/src/components/Checkbox/Checkbox.stories.mdx, packages/core/src/components/Checkbox/Checkbox.styled.tsx, packages/core/src/components/Checkbox/__snapshots__/checkbox.test.tsx.snap, packages/core/src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/core/src/components/Radio/Radio.stories.mdx, packages/core/src/components/Radio/Radio.styled.tsx, packages/core/src/components/Radio/__snapshots__/radio.test.tsx.snap, packages/core/src/components/RadioGroup/__snapshots__/RadioGroup.test.tsx.snap, packages/core/src/components/Table/Body/Cell/__snapshots__/Cell.test.tsx.snap, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap, packages/theme/src/core/checkbox/index.ts, packages/theme/src/core/checkbox/types.ts, packages/theme/src/core/radio/index.ts, packages/theme/src/core/radio/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat(core, theme): adds pressed state to checkbox and radio components

packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix padding of HeadCell button for ‘XS’ tablesize

packages/core/src/components/Checkbox/Checkbox.stories.mdx, packages/core/src/components/Checkbox/Checkbox.styled.tsx, packages/core/src/components/Checkbox/__snapshots__/checkbox.test.tsx.snap, packages/core/src/components/CheckboxGroup/__snapshots__/CheckboxGroup.test.tsx.snap, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/core/src/components/Table/Body/Cell/__snapshots__/Cell.test.tsx.snap, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix(core): updates border-color of selectors when hovered/pressed based on fill-color

packages/core/src/components/Table/Body/Cell/RowActionsCell/RowActionsCell.styled.tsx, packages/core/src/components/Table/Body/Cell/Styled/Cell.styled.tsx, packages/core/src/components/Table/Body/GroupedRow/TitleRow/TitleRow.styled.tsx, packages/core/src/components/Table/Body/Row/Row.styled.tsx, packages/core/src/components/Table/Body/Row/__snapshots__/Row.test.tsx.snap, packages/core/src/components/Table/GroupCell/GroupCell.styled.tsx, packages/core/src/components/Table/GroupCell/__snapshots__/GroupCell.test.tsx.snap, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap, packages/theme/src/core/table/index.ts, packages/theme/src/core/table/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat(core): add prop to switch between row highlighter outlined and shadow

README.md, packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/forms/src/components/Form/Form.test.tsx, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
-   [ ] Bugfix
Small changes to README
-   [ ] Yes
-   [x] No
=> Fix: small cleanup changes to README

docs/Introduction.stories.mdx, packages/layout/README.md, packages/loaders/README.md, packages/theme/README.md, packages/utils/README.md
affects: @medly-components/layout, @medly-components/loaders, @medly-components/theme,
@medly-components/utils
-   [ ] Bugfix
Minor updates to documentation
-   [ ] Yes
-   [x] No
Add any other context or screenshots about the feature …
=> feat: minor README/documentation updates

packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx, packages/core/src/components/Table/Head/HeadCell/HeadCell.tsx, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap, packages/theme/src/core/table/index.ts, packages/theme/src/core/table/types.ts
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: fontVariant issue in table head cell component

packages/core/src/components/Table/Body/Cell/Styled/CustomComponentWrapper.styled.tsx
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix(core): fix fitContent table cell width issue for custom cell component

.github/workflows/release.yml
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: add token while checking out the branch

packages/core/src/components/Table/GroupCell/GroupCell.styled.tsx, packages/core/src/components/Table/GroupCell/GroupCell.test.tsx, packages/core/src/components/Table/GroupCell/__snapshots__/GroupCell.test.tsx.snap, packages/core/src/components/Table/GroupCell/types.ts, packages/core/src/components/Table/Head/Head.tsx, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix grouped content cell right border issue

yarn.lock
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix build error

packages/core/src/components/DatePicker/__snapshots__/DatePicker.test.tsx.snap, packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/core/src/components/Popover/Popover.stories.mdx, packages/core/src/components/Popover/Popover.stories.tsx
@gmukul01 as promised 🙂 
I updated the previews as I found fit, I will probably be doing a few more of these, so let me know if there are any code/documentation style changes you would like for this and fir the future.
-   [ ] Bugfix
- …
=> docs: improve popover storybook previews

packages/utils/src/hooks/useSWRAxios/types.ts, packages/utils/src/hooks/useSWRAxios/useSWRAxios.stories.mdx, packages/utils/src/hooks/useSWRAxios/useSWRAxios.ts
-   [x] Bugfix
We were using the the whole request object as the key.
Now we will use only the url to use as the key.
-   [ ] Yes
-   [x] No
=> fix: change the key of swr from request object to url

.github/workflows/release.yml, lerna.json
-   [ ] Bugfix
-   [x] CI related changes
=> fix: trigger release workflow on push instead of pull_request merge

packages/core/src/components/Table/Table.tsx, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap, packages/core/src/components/Table/docs/Table.stories.mdx, packages/core/src/components/Table/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor(core): remove withActionBar prop from table component

packages/core/src/components/Button/Button.stories.tsx, packages/core/src/components/Button/Button.styled.tsx, packages/core/src/components/Button/Button.test.tsx, packages/core/src/components/Button/Button.tsx, packages/core/src/components/Button/Loader/types.ts, packages/core/src/components/Button/styles/flatButton.tsx, packages/core/src/components/Button/styles/outlinedButton.tsx, packages/core/src/components/Button/styles/solidButton.tsx, packages/core/src/components/Button/types.ts, packages/core/src/components/Toast/types.ts, packages/forms/src/components/Actions/Actions.tsx, packages/forms/src/components/Actions/types.ts, packages/forms/src/components/Fields/Fields.components.tsx, packages/forms/src/components/Fields/types.ts, packages/forms/src/components/Form/Form.stories.mdx, packages/forms/src/components/Form/Form.tsx, packages/forms/src/components/Form/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat: add `isLoading` prop to form component

packages/core/src/components/Avatar/Avatar.stories.tsx, packages/core/src/components/Avatar/Avatar.tsx, packages/core/src/components/Avatar/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> refactor: change avatar prop name to AvatarProps

packages/core/src/components/Card/Card.stories.tsx, packages/core/src/components/Card/Card.styled.tsx, packages/core/src/components/Card/Card.test.tsx, packages/core/src/components/Card/Card.tsx, packages/core/src/components/Card/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> refactor: change card prop name to CardProps

packages/core/src/components/Checkbox/Checkbox.stories.tsx, packages/core/src/components/Checkbox/Checkbox.styled.tsx, packages/core/src/components/Checkbox/Checkbox.tsx, packages/core/src/components/Checkbox/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change checkbox prop name to CheckboxProps

packages/core/src/components/CheckboxGroup/CheckboxGroup.stories.tsx, packages/core/src/components/CheckboxGroup/CheckboxGroup.tsx, packages/core/src/components/CheckboxGroup/getValuesFromOptions.ts, packages/core/src/components/CheckboxGroup/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change checkboxgroup prop name to CheckboxGroupProps

packages/core/src/components/CardTable/CardTable.tsx, packages/core/src/components/CardTable/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> refactor: change cardtable prop name to CardTableProps

packages/core/src/components/Chip/Chip.stories.tsx, packages/core/src/components/Chip/Chip.tsx, packages/core/src/components/Chip/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change chip prop name to ChipProps

packages/core/src/components/DialogBox/DialogBox.test.tsx, packages/core/src/components/DialogBox/DialogBox.tsx, packages/core/src/components/DialogBox/Header/Header.styled.tsx, packages/core/src/components/DialogBox/Header/types.ts, packages/core/src/components/DialogBox/Popup/Popup.styled.tsx, packages/core/src/components/DialogBox/Popup/Popup.test.tsx, packages/core/src/components/DialogBox/Popup/Popup.tsx, packages/core/src/components/DialogBox/Popup/types.ts, packages/core/src/components/DialogBox/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change dialogbox prop name to DialogBoxProps

packages/core/src/components/FileInput/FileInput.stories.tsx, packages/core/src/components/FileInput/FileInput.tsx, packages/core/src/components/FileInput/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change fileinput prop name to FileInputProps

packages/core/src/components/Drawer/Drawer.tsx, packages/core/src/components/Drawer/Footer/Footer.styled.tsx, packages/core/src/components/Drawer/Footer/Footer.tsx, packages/core/src/components/Drawer/Footer/types.ts, packages/core/src/components/Drawer/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change drawer prop name to DrawerProps

packages/core/src/components/FieldWithLabel/FieldWithLabel.tsx, packages/core/src/components/FieldWithLabel/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change fieldwithlabel prop name to FieldWithLabelProps

packages/core/src/components/Pagination/PaginationPopup/PaginationPopup.tsx, packages/core/src/components/Pagination/PaginationPopup/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change pagination popup prop name to PaginationPopupProps

packages/core/src/components/Popover/Popover.styled.tsx, packages/core/src/components/Popover/Popover.tsx, packages/core/src/components/Popover/Popup/Popup.test.tsx, packages/core/src/components/Popover/Popup/Popup.tsx, packages/core/src/components/Popover/Popup/styled/Popup.styled.tsx, packages/core/src/components/Popover/Popup/styled/WithArrow.tsx, packages/core/src/components/Popover/Popup/types.ts, packages/core/src/components/Popover/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change popover prop name to PopoverProps

packages/core/src/components/Input/Input.stories.tsx, packages/core/src/components/Input/Input.styled.tsx, packages/core/src/components/Input/Input.tsx, packages/core/src/components/Input/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change input prop name to InputProps

packages/core/src/components/List/List.stories.tsx, packages/core/src/components/List/List.styled.tsx, packages/core/src/components/List/List.tsx, packages/core/src/components/List/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change list prop name to ListProps

packages/core/src/components/Link/Link.tsx, packages/core/src/components/Link/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change link prop name to LinkProps

packages/core/src/components/Radio/Radio.stories.tsx, packages/core/src/components/Radio/Radio.styled.tsx, packages/core/src/components/Radio/Radio.tsx, packages/core/src/components/Radio/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change radio prop name to RadioProps

packages/core/src/components/RadioGroup/RadioGroup.stories.tsx, packages/core/src/components/RadioGroup/RadioGroup.tsx, packages/core/src/components/RadioGroup/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change radiogroup prop name to RadioGroupProps

packages/core/src/components/Stepper/Stepper.stories.tsx, packages/core/src/components/Stepper/Stepper.test.tsx, packages/core/src/components/Stepper/Stepper.tsx, packages/core/src/components/Stepper/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change stepper prop name to StepperProps

packages/core/src/components/SearchBox/SearchBox.stories.tsx, packages/core/src/components/SearchBox/SearchBox.styled.tsx, packages/core/src/components/SearchBox/SearchBox.test.tsx, packages/core/src/components/SearchBox/SearchBox.tsx, packages/core/src/components/SearchBox/styles/icons.tsx, packages/core/src/components/SearchBox/styles/options.tsx, packages/core/src/components/SearchBox/styles/utils.tsx, packages/core/src/components/SearchBox/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change searchbox prop name to SearchBoxProps

packages/core/src/components/ToastContainer/ToastContainer.component.tsx, packages/core/src/components/ToastContainer/ToastContainer.stories.tsx, packages/core/src/components/ToastContainer/ToastContainer.styled.tsx, packages/core/src/components/ToastContainer/ToastContainer.test.tsx, packages/core/src/components/ToastContainer/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change toastcontainer prop name to ToastContainerProps

packages/core/src/components/Text/Text.styled.tsx, packages/core/src/components/Text/Text.tsx, packages/core/src/components/Text/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change text prop name to Textprops

packages/core/src/components/Tabs/Tab/Tab.test.tsx, packages/core/src/components/Tabs/Tab/Tab.tsx, packages/core/src/components/Tabs/Tab/types.ts, packages/core/src/components/Tabs/TabList/TabList.tsx, packages/core/src/components/Tabs/TabList/types.ts, packages/core/src/components/Tabs/TabPanel/TabPanel.tsx, packages/core/src/components/Tabs/TabPanel/types.ts, packages/core/src/components/Tabs/Tabs.test.tsx, packages/core/src/components/Tabs/Tabs.tsx, packages/core/src/components/Tabs/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change tabs prop name

packages/core/src/components/Toggle/Toggle.stories.tsx, packages/core/src/components/Toggle/Toggle.styled.tsx, packages/core/src/components/Toggle/Toggle.tsx, packages/core/src/components/Toggle/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change toggle prop name to ToggleProps

packages/core/src/components/Table/Body/Body.tsx, packages/core/src/components/Table/Body/GroupedRow/ContentRow/ContentRow.tsx, packages/core/src/components/Table/Body/GroupedRow/ContentRow/types.ts, packages/core/src/components/Table/Body/GroupedRow/GroupedRow.tsx, packages/core/src/components/Table/Body/GroupedRow/TitleRow/TitleRow.tsx, packages/core/src/components/Table/Body/GroupedRow/TitleRow/types.ts, packages/core/src/components/Table/Body/GroupedRow/types.ts, packages/core/src/components/Table/Body/Row/Row.tsx, packages/core/src/components/Table/Body/Row/types.ts, packages/core/src/components/Table/Body/types.ts, packages/core/src/components/Table/ColumnConfiguration/ColumnConfiguration.tsx, packages/core/src/components/Table/ColumnConfiguration/types.ts, packages/core/src/components/Table/GroupCell/GroupCell.styled.tsx, packages/core/src/components/Table/GroupCell/types.ts, packages/core/src/components/Table/Head/Head.tsx, packages/core/src/components/Table/Head/HeadRow/HeadRow.styled.tsx, packages/core/src/components/Table/Head/HeadRow/types.ts, packages/core/src/components/Table/Head/types.ts, packages/core/src/components/Table/Minimap/Minimap.tsx, packages/core/src/components/Table/Minimap/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change table props name to TableProps

packages/core/src/components/Modal/Header/types.ts, packages/core/src/components/Modal/Modal.test.tsx, packages/core/src/components/Modal/Modal.tsx, packages/core/src/components/Modal/Popup/Popup.styled.tsx, packages/core/src/components/Modal/Popup/Popup.test.tsx, packages/core/src/components/Modal/Popup/Popup.tsx, packages/core/src/components/Modal/Popup/types.ts, packages/core/src/components/Modal/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change modal props name to ModalProps

packages/core/src/components/Label/Label.styled.tsx, packages/core/src/components/Label/Label.tsx, packages/core/src/components/Label/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: change label prop name to LabelProps

packages/core/src/components/ToastContainer/ToastContainer.component.tsx, packages/core/src/components/ToastContainer/ToastContainer.test.tsx, packages/core/src/components/ToastContainer/__snapshots__/ToastContainer.test.tsx.snap
-   [x] Bugfix
We are rendering toast container even if there are no toasts available.
Remove toast container if there are no toasts available.
-   [ ] Yes
-   [x] No
=> fix: remove toast container if there are no toasts available

.github/workflows/lint-build-test.yml
-   [ ] Bugfix
-   [x] CI related changes
-   [ ] Yes
-   [x] No
=> feat: run lint, build & test workflow on pull request as well

packages/core/src/components/CssBaseline/fonts.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: ensure text remains visible during webfont load

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/story.md, .github/PULL_REQUEST_TEMPLATE.md, docs/Colors/Colors.stories.mdx, docs/Introduction.stories.mdx, packages/core/src/components/Breadcrumb/Breadcrumb.stories.mdx, packages/core/src/components/Button/Button.stories.mdx, packages/core/src/components/Card/Card.stories.mdx, packages/core/src/components/CenterAlignedLoader/CenterAlignedLoader.stories.mdx
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> docs: Made editorial changes to some pages.

packages/core/src/components/SearchBox/styles/icons.tsx, packages/theme/src/core/searchBox/index.ts, packages/theme/src/core/searchBox/types.ts
-   [ ] Bugfix
This PR adds `active` to the expandIcon color
-   [ ] Yes
-   [x] No
=> feat: updating theme to include searchBox expandIcon active state

packages/core/src/components/DateRangePicker/DateRangePicker.tsx, packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix date range picker min width issue

packages/layout/src/components/Header/Header.styled.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> refactor: use header html tag for Header component

packages/utils/src/hooks/useKeyPress/useKeyPress.ts
-   [ ] Bugfix
-   [x] Performance improves
-   [ ] Yes
-   [x] No
=> perf(utils): returns function if same key is pressed more than one time

packages/core/src/components/Logo/Logo.styled.tsx, packages/core/src/components/Logo/Logo.test.tsx, packages/core/src/components/Logo/Logo.tsx, packages/core/src/components/Logo/types.ts, packages/layout/src/components/SideNav/MedlySidenavHeader/__snapshots__/MedlySidenavHeader.test.tsx.snap
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: add onClick prop in Logo component

packages/core/src/components/DateRangePicker/DateRangePicker.test.tsx, packages/core/src/components/DateRangePicker/helpers/dateRangeHelpers.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): update the start day of the date range's current week selection

packages/utils/src/hooks/useAxios/useAxios.ts
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: update component after unmount in useAxios hook

packages/core/src/components/MultiSelect/MultiSelect.styled.tsx, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: default color of chevron icon in multiSelect component

packages/core/src/components/SearchBox/SearchBox.tsx
-   [x] Bugfix
`handleOptionClick` now has the dependency `onOptionSelected`
-   [ ] Yes
-   [x] No
=> fix: adding in critical dependency for handleOptionClick

packages/layout/src/components/Header/Header.tsx, packages/layout/src/components/Header/NavItem/NavItem.styled.tsx
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: add Style attribute in Header component

README.md
-   [ ] Bugfix
-   [x] Other... Please describe: https in URL for hero image
-   [ ] Yes
-   [x] No
=> fix: Use https for hero image

packages/utils/src/hooks/useAxios/useAxios.stories.mdx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> docs: update useAxios docs

jest.config.js, packages/core/src/components/SingleSelect/SingleSelect.tsx
-   [x] Bugfix
Wrong validation message showing in single select component.
Handled all error handling scenario.
-   [ ] Yes
-   [x] No
=> fix: singleSelect component error message issue

packages/core/src/components/DatePicker/DatePicker.test.tsx, packages/core/src/components/DatePicker/DatePicker.tsx, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap, packages/forms/src/components/Form/testSchema.ts
-   [x] Bugfix
If we focus on datepicker and then try to select year/month it gives validation error.
It will validate only when we click outside of the component.
-   [ ] Yes
-   [x] …
=> fix: wrong error validation in datepicker component

packages/utils/src/helpers/localStorage/localStorage.ts, packages/utils/src/helpers/sessionStorage/sessionStorage.ts, packages/utils/src/hooks/useStorage/useStorage.ts
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: window object undefined in local and session storage

packages/layout/src/components/Header/Nav/Nav.tsx
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: context undefined issue in header nav component in cjs

packages/core/src/components/CssBaseline/fonts.tsx, packages/theme/src/core/font/faces.ts, packages/theme/src/core/font/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: add font display in font face

packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap, packages/theme/src/core/table/index.ts, packages/theme/src/core/table/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat: adding border radius for table header cell into theme

packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap, packages/core/src/components/SearchBox/styles/icons.tsx
- Moved border radius property out of hover state.
- Show search icon hover styles when input field isnt selected.
- Fix hover styles on search icon
-   [x] Bugfix
-   [ ] Yes
-   [ ] No
Provide any additional …
=> fix searchBox component

packages/forms/src/components/Fields/types.ts, packages/forms/src/components/Form/Form.test.tsx, packages/forms/src/components/Form/stories/AddPhoneNumber.tsx, packages/forms/src/components/Form/stories/AdvancedForm.stories.mdx, packages/forms/src/components/Form/stories/CustomPhoneField.tsx, packages/forms/src/components/Form/stories/Form.stories.tsx, packages/forms/src/components/Form/types.ts, packages/forms/src/components/index.ts
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: types of custom component in forms package

packages/core/src/components/Modal/CloseIcon/CloseIcon.styled.tsx, packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap, packages/theme/src/core/modal/index.ts, packages/theme/src/core/modal/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat(theme): allow adding border to modal close icon

CONTRIBUTING.md
affects: @medly-components/core, @medly-components/forms, @medly-components/icons,
@medly-components/layout, @medly-components/loaders, @medly-components/theme,
@medly-components/utils
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
Provide any …
=> docs: adds props naming rules to `contributing.md` file

packages/core/src/components/CssBaseline/CssBaseline.styled.tsx, packages/core/src/components/DateRangePicker/DateRangePicker.test.tsx, packages/core/src/components/DateRangePicker/DateRangePicker.tsx, packages/core/src/components/DateRangePicker/DateRangeTextFields/DateRangeTextFields.tsx, packages/core/src/components/DateRangePicker/DateRangeTextFields/types.ts, packages/core/src/components/DateRangePicker/DateRangeTextFields/useDateRangeTextFieldsHandlers.ts, packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: validation meesage issue in DateRangePicker component

packages/utils/src/hooks/useStorage/useStorage.ts
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: empty string as initialValue in useStorage

packages/utils/src/hooks/useStorage/useStorage.ts
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: update state issue when component is unmounted

packages/core/src/components/MultiSelect/MultiSelect.test.tsx, packages/core/src/components/MultiSelect/MultiSelect.tsx, packages/core/src/components/MultiSelect/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: add onInputChange prop in MultiSelect component

packages/core/src/components/Table/Head/HeadCell/HeadCell.styled.tsx, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [ ] No
=> Center aligning table header text

packages/core/src/components/Table/Body/Cell/Cell.tsx, packages/core/src/components/Table/Body/Row/Row.styled.tsx, packages/core/src/components/Table/Body/Row/__snapshots__/Row.test.tsx.snap, packages/core/src/components/Table/Table.test.tsx, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
-   [x] Bugfix
Right now default fontVariant will be applied to all the Text component used anywhere in Table Row component.
Default fontVariant will be applied only to `Text` component used directly in Cell …
=> fix: style issue of text component used in table rows

packages/loaders/src/loaders/CircleLoader.tsx, packages/loaders/src/loaders/ConcentricCircleLoader.tsx, packages/loaders/src/loaders/DotsBouncingLoader.tsx, packages/loaders/src/loaders/DotsLoader.tsx
affects: @medly-components/loaders
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: strict null check in loaders package

packages/forms/src/components/Actions/Actions.tsx, packages/forms/src/components/Actions/types.ts, packages/forms/src/components/Fields/Fields.components.tsx, packages/forms/src/components/Form/Form.test.tsx, packages/forms/src/components/Form/Form.tsx, packages/forms/src/components/Form/__snapshots__/Form.test.tsx.snap, packages/forms/src/components/Form/types.ts, packages/forms/src/hooks/useForm/types.ts, packages/forms/src/hooks/useForm/useForm.ts, packages/layout/src/components/SideNav/NavItem/NavItem.tsx
affects: @medly-components/forms, @medly-components/layout
-   [x] Bugfix
Fixed all strict null check issues in forms package.
-   [ ] Yes
-   [x] No
=> fix: strict null check in forms package

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> docs: made changes to readme, contributing, and Code of conduct.

packages/core/src/components/Toast/Toast.tsx, packages/core/src/components/Toast/types.ts
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: css prop issue in toast component

packages/core/src/components/Stepper/Stepper.stories.tsx, packages/core/src/components/Stepper/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> fix: strict null check issue in stepper component

packages/core/src/components/Radio/Radio.stories.tsx, packages/core/src/components/Radio/Radio.styled.tsx, packages/core/src/components/Radio/Radio.tsx, packages/core/src/components/Radio/radio.test.tsx, packages/core/src/components/Radio/types.ts, packages/core/src/components/RadioGroup/RadioGroup.stories.tsx, packages/core/src/components/RadioGroup/RadioGroup.test.tsx, packages/core/src/components/RadioGroup/RadioGroup.tsx, packages/core/src/components/RadioGroup/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> fix: strict null check for Radio and RadioGroup component

packages/core/src/components/SearchBox/SearchBox.styled.tsx, packages/core/src/components/SearchBox/SearchBox.test.tsx, packages/core/src/components/SearchBox/SearchBox.tsx, packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap, packages/core/src/components/SearchBox/styles/icons.tsx, packages/core/src/components/SearchBox/styles/options.tsx, packages/core/src/components/SearchBox/styles/utils.tsx, packages/core/src/components/SearchBox/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> fix: strict null check issue in searchbox component

jest.setupAfterEnv.js, package.json, packages/core/src/components/Avatar/Avatar.test.tsx, packages/core/src/components/Avatar/__snapshots__/Avatar.test.tsx.snap, packages/core/src/components/Table/helpers.ts, packages/core/src/components/TextField/getMaskedValue.ts, packages/core/src/components/ToastContainer/ToastStore.ts, yarn.lock
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: fix regex Denial of service and Weak Cryptography issue

packages/core/src/components/Table/helpers.ts, packages/core/src/components/TextField/getMaskedValue.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> refactor: mark false positive for sonar regex warning

packages/markdown/src/components/MarkdownContent/CodeBlock.tsx, packages/markdown/src/components/MarkdownContent/tomorrow.ts
affects: @medly-components/markdown
-   [ ] Bugfix
-   [x] Code style update (formatting, local variables)
-   [ ] Yes
-   [x] No
=> refactor(markdown): extract out tomorrow prism theme

packages/markdown/src/components/MarkdownContent/MarkdownContent.stories.mdx, packages/markdown/src/components/MarkdownContent/MarkdownContent.tsx, packages/markdown/src/components/MarkdownContent/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> Markdown: Add allowElements props 

packages/forms/src/components/Fields/Fields.components.tsx
Currently the `Fields` component does not display the integer `0` for `type === 'number'`. 
Updating `Fields` component to display the integer `0`.
-   [X] Bugfix
-   [ ] Yes
-   [ ] No
=> feat(core): fix number field to display int 0

packages/utils/src/hooks/useWindowSize/index.ts, packages/utils/src/hooks/useWindowSize/useWindowSize.stories.mdx, packages/utils/src/hooks/useWindowSize/useWindowSize.test.tsx, packages/utils/src/hooks/useWindowSize/useWindowSize.ts
-   [ ] Bugfix
No docs for useWindowSize
#443 
added docs for useWindowSize
-   [ ] Yes
-   [x] No
=> doc: add documentation for useWindowSize in utils package

packages/core/src/components/TextField/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> docs(core): update withCharacterCount prop description

packages/core/src/components/Table/Body/Row/Row.tsx, packages/core/src/components/Table/docs/filterData.ts, packages/core/src/components/Table/helpers.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat(core): `field` value in tableConfig to accept dot notation

babel.config.js
-   [ ] Bugfix
-   [x] Build related changes
Fixes `react-testing-library` React import errors
-   [ ] Yes
-   [x] No
=> fix: set babel plugin-transform-react-jsx runtime to automatic

packages/loaders/src/LoaderContainer/LoaderContainer.tsx, packages/loaders/src/Loaders.stories.tsx, packages/loaders/src/loaders/CircleLoader.tsx, packages/loaders/src/loaders/ConcentricCircleLoader.tsx, packages/loaders/src/loaders/DotsBouncingLoader.tsx, packages/loaders/src/loaders/DotsLoader.tsx
affects: @medly-components/loaders
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> Remove react imports: loaders

packages/layout/src/components/Header/Header.context.tsx, packages/layout/src/components/Header/Header.test.tsx, packages/layout/src/components/Header/Header.tsx, packages/layout/src/components/Header/Nav/Nav.test.tsx, packages/layout/src/components/Header/Nav/Nav.tsx, packages/layout/src/components/Header/types.ts, packages/layout/src/components/SideNav/MedlySidenavHeader/MedlySidenavHeader.test.tsx, packages/layout/src/components/SideNav/MedlySidenavHeader/MedlySidenavHeader.tsx, packages/layout/src/components/SideNav/NavGroup/NavGroup.tsx, packages/layout/src/components/SideNav/NavItem/NavItem.test.tsx, packages/layout/src/components/SideNav/NavItem/NavItem.tsx, packages/layout/src/components/SideNav/NavList/NavList.test.tsx, packages/layout/src/components/SideNav/SideNav.context.tsx, packages/layout/src/components/SideNav/SideNav.stories.tsx, packages/layout/src/components/SideNav/SideNav.test.tsx, packages/layout/src/components/SideNav/SideNav.tsx, packages/layout/src/components/SideNav/ToggleSwitch/ToggleSwitch.test.tsx, packages/layout/src/components/SideNav/ToggleSwitch/ToggleSwitch.tsx, packages/layout/src/components/SideNav/types.ts, packages/layout/src/components/SidePanel/SidePanel.test.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> Remove react imports: layout

packages/utils/src/components/InjectClassName/InjectClassName.test.tsx, packages/utils/src/components/InjectClassName/InjectClassName.tsx, packages/utils/src/hooks/useAxios/useAxios.test.tsx, packages/utils/src/hooks/useKeyPress/useKeyPress.stories.tsx, packages/utils/src/hooks/useKeyPress/useKeyPress.test.tsx, packages/utils/src/hooks/useMediaQuery/useMediaQuery.ts, packages/utils/src/hooks/useOuterClickNotifier/useOuterClickNotifier.test.tsx, packages/utils/src/hooks/useOuterClickNotifier/useOuterClickNotifier.ts, packages/utils/src/hooks/useSWRAxios/useSWRAxios.test.tsx, packages/utils/src/hooks/useStorage/useStorage.test.tsx, packages/utils/src/hooks/useWindowSize/useWindowSize.test.tsx, packages/utils/src/style/centerAligned/centerAligned.test.tsx, packages/utils/src/style/getFontStyle/getFontStyle.test.tsx, packages/utils/src/test-utils.tsx, packages/utils/src/types/HTMLProps.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> Remove react imports: utils

packages/utils/src/helpers/updateNestedValue/updateNestedValue.test.ts, packages/utils/src/helpers/updateNestedValue/updateNestedValue.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> refactor: updateNestedValue function to accept any type

packages/forms/src/components/Actions/Actions.test.tsx, packages/forms/src/components/Actions/Actions.tsx, packages/forms/src/components/Fields/Fields.components.tsx, packages/forms/src/components/Form/Form.test.tsx, packages/forms/src/components/Form/Form.tsx, packages/forms/src/components/Form/stories/AddPhoneNumber.tsx, packages/forms/src/components/Form/stories/CustomPhoneField.tsx, packages/forms/src/components/Form/stories/Form.stories.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> Remove react imports: forms

packages/markdown/src/components/MarkdownContent/CodeBlock.tsx, packages/markdown/src/components/MarkdownContent/MarkdownContent.tsx, packages/markdown/src/components/MarkdownContent/Youtube.tsx
affects: @medly-components/markdown
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> Remove react imports: markdown

packages/theme/src/core/colors/apricot.ts, packages/theme/src/core/colors/blue.ts, packages/theme/src/core/colors/blush.ts, packages/theme/src/core/colors/classyGreen.ts, packages/theme/src/core/colors/everGreen.ts, packages/theme/src/core/colors/green.ts, packages/theme/src/core/colors/heartbeat.ts, packages/theme/src/core/colors/index.ts, packages/theme/src/core/colors/medlyGreen.ts, packages/theme/src/core/colors/periwinkle.ts, packages/theme/src/core/colors/red.ts, packages/theme/src/core/colors/types.ts, packages/theme/src/core/colors/yellow.ts
affects: @medly-components/theme
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: add new colors

packages/core/src/components/Table/useRowSelector.ts
-   [x] Bugfix
-   [ ] Yes
-   [ ] No
=> fix(core): fix table select all issue when rowSelectionDisableKey is not provided

packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, packages/core/src/components/TextField/__snapshots__/TextField.test.tsx.snap, packages/theme/src/core/textField/index.ts
affects: @medly-components/theme
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor: update TextField Variant "Fusion" Border Radius

packages/core/src/components/MultiSelect/MultiSelect.test.tsx, packages/core/src/components/MultiSelect/Options/Options.tsx
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: selecting option with numeric value

packages/core/src/components/Chip/Chip.stories.mdx, packages/core/src/components/CssBaseline/CssBaseline.stories.mdx, packages/core/src/components/DatePicker/DatePicker.stories.mdx, packages/core/src/components/DatePicker/types.ts, packages/core/src/components/DateRangePicker/DateRangePicker.stories.mdx
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> DS | Editorial Changes

packages/core/src/components/MultiSelect/MultiSelect.stories.mdx, packages/core/src/components/MultiSelect/MultiSelect.test.tsx, packages/core/src/components/MultiSelect/MultiSelect.tsx, packages/core/src/components/MultiSelect/Options/Chip/Chip.tsx, packages/core/src/components/MultiSelect/Options/Options.tsx, packages/core/src/components/MultiSelect/Options/types.ts, packages/core/src/components/MultiSelect/helpers.ts, packages/core/src/components/MultiSelect/types.ts, packages/core/src/components/SingleSelect/Options/Option/Option.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: Multi select component to have creatable options

packages/core/src/components/Button/Button.stories.mdx, packages/core/src/components/Button/Button.test.tsx, packages/core/src/components/Button/__snapshots__/Button.test.tsx.snap, packages/core/src/components/Button/styles/flatButton.tsx, packages/core/src/components/Button/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> feat: add hideUnderline prop to toggle flat variant button text underline

packages/core/src/components/Table/Head/HeadCell/HeadCell.tsx
-   [x] Bugfix
Whenever we resize any column other column widths also changes.
Resizing any column will not effect any other column.
-   [ ] Yes
-   [x] No
=> fix: table cell shrinking issue on resizing any column

packages/core/src/components/Table/Body/Body.tsx, packages/core/src/components/Table/Body/Cell/RowActionsCell/RowActionsCell.styled.tsx, packages/core/src/components/Table/Body/Cell/RowActionsCell/RowActionsCell.tsx, packages/core/src/components/Table/Body/Cell/RowActionsCell/types.ts, packages/core/src/components/Table/Body/Row/Row.styled.tsx, packages/core/src/components/Table/Body/Row/Row.tsx, packages/core/src/components/Table/Body/Row/types.ts, packages/core/src/components/Table/Body/types.ts, packages/core/src/components/Table/Table.tsx, packages/core/src/components/Table/docs/Table.stories.mdx, packages/core/src/components/Table/types.ts
-   [ ] Bugfix
You can navigate rows in table using `Up Arrow` and `Down Arrow` key. To select a row you can use `x` key whereas you can expand a row using the `space` key.
-   [ ] Yes
-   [x] No
Provide any additional context or screenshots …
=> feat: Add keyboard navigation to table component

packages/core/src/components/Table/Body/Body.tsx, packages/core/src/components/Table/Body/Row/Row.styled.tsx, packages/core/src/components/Table/Body/Row/Row.tsx, packages/core/src/components/Table/Body/Row/types.ts, packages/core/src/components/Table/Body/types.ts, packages/core/src/components/Table/Table.tsx, packages/core/src/components/Table/constants.ts, packages/core/src/components/Table/context/TableComponentsCommonProps.context.tsx, packages/core/src/components/Table/docs/Table.stories.mdx, packages/core/src/components/Table/types.ts
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: add left and right arrow to expand and collapse row

packages/core/src/components/MultiSelect/MultiSelect.test.tsx, packages/core/src/components/MultiSelect/Options/Options.tsx
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: fix multiselect tests

packages/core/src/components/MultiSelect/MultiSelect.test.tsx, packages/core/src/components/MultiSelect/Options/Options.tsx, packages/core/src/components/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: the content to be passed to onChange prop of MultiSelect component

packages/core/src/components/DialogBox/Popup/Popup.styled.tsx, packages/core/src/components/DialogBox/Popup/__snapshots__/Popup.test.tsx.snap, packages/core/src/components/DialogBox/__snapshots__/DialogBox.test.tsx.snap, packages/core/src/components/Modal/Popup/__snapshots__/Popup.test.tsx.snap, packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap, packages/theme/src/core/dialog-box/index.ts, packages/theme/src/core/modal/index.ts
-   [ ] Bugfix
-   [x] Style
-   [ ] Yes
-   [x] No
=> style: update border radius of modal and dialog box

packages/core/src/components/MultiSelect/MultiSelect.test.tsx, packages/core/src/components/MultiSelect/Options/Options.tsx, packages/core/src/components/Table/Body/Body.tsx
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: editing textfield problem due to table keyboard event

packages/core/src/components/MultiSelect/MultiSelect.test.tsx, packages/core/src/components/MultiSelect/MultiSelect.tsx, packages/core/src/components/MultiSelect/Options/Options.tsx, packages/core/src/components/MultiSelect/Options/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: create multi-select option on enter keypress

README.md, packages/core/package.json, packages/core/src/components/Box/Box.stories.mdx, packages/core/src/components/Box/Box.stories.tsx, packages/core/src/components/Box/Box.styled.tsx, packages/core/src/components/Box/Box.test.tsx, packages/core/src/components/Box/Box.tsx, packages/core/src/components/Box/__snapshots__/Box.test.tsx.snap, packages/core/src/components/Box/index.ts, packages/core/src/components/Box/types.ts, packages/core/src/components/index.ts, packages/core/src/types.ts
-   [ ] Bugfix
Add `Box` component.
-   [ ] Yes
-   [x] No
=> feat: add Box component

packages/utils/src/hooks/useStorage/useStorage.ts
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: useStorage eventlistner issue

packages/core/src/components/Table/Foot/Foot.test.tsx, packages/core/src/components/Table/Foot/Foot.tsx, packages/core/src/components/Table/Foot/__snapshots__/Foot.test.tsx.snap, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> test: add test cases for table foot

packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, packages/theme/src/core/singleSelect/index.ts
-   [ ] Bugfix
-   [x] Css Style
-   [ ] Yes
-   [x] No
=> style: update single select border radius as per new design

packages/core/src/components/Logo/Logo.tsx, packages/layout/src/components/Header/Header.styled.tsx, packages/layout/src/components/Header/Header.tsx, packages/layout/src/components/Header/Nav/Nav.tsx, packages/layout/src/components/Header/NavItem/NavItem.styled.tsx, packages/layout/src/components/Header/NavItem/NavItem.test.tsx, packages/layout/src/components/Header/NavItem/__snapshots__/NavItem.test.tsx.snap, packages/theme/src/core/colors/types.ts, packages/theme/src/layout/header/index.ts, packages/theme/src/layout/header/types.ts
affects: @medly-components/core, @medly-components/layout, @medly-components/theme
BREAKING CHANGE:
theme structure of header component is changed to accomodate new style
-   [ ] Bugfix
-   [x] Yes
-   [ ] No
=> feat: update header component style as per new style

.storybook/main.js, .storybook/preview.js, package.json, packages/core/src/components/CardTable/docs/CardTable.stories.mdx, packages/core/src/components/Input/Input.stories.mdx, yarn.lock
-   [ ] Bugfix
Adds deprecated label to `CardTable` and `Input` element
-   [ ] Yes
-   [x] No
=> feat: add labels for storybook components

packages/forms/src/components/Form/stories/Form.stories.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> docs: add number type to form docs

packages/core/src/components/CheckboxGroup/CheckboxGroup.tsx, packages/core/src/components/CheckboxGroup/types.ts, packages/core/src/components/CheckboxGroup/useCheckboxGroupKeyboardNavigation.ts, packages/core/src/components/CheckboxGroup/useKeyboardNavigation.ts, packages/core/src/components/MultiSelect/MultiSelect.tsx, packages/core/src/components/MultiSelect/types.ts, packages/core/src/components/MultiSelect/useKeyboardNavigation.ts
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> refactor(multiselect):  keyboard navigation

packages/utils/src/hooks/useAxios/useAxios.ts, packages/utils/src/hooks/useCombinedRefs/useCombinedRefs.ts, packages/utils/src/hooks/useMediaQuery/useMediaQuery.ts, packages/utils/src/hooks/useOuterClickNotifier/useOuterClickNotifier.ts, packages/utils/src/hooks/useSWRAxios/useSWRAxios.stories.mdx, packages/utils/src/hooks/useSWRAxios/useSWRAxios.ts, packages/utils/src/hooks/useStorage/useStorage.ts, packages/utils/src/hooks/useUpdateEffect/useUpdateEffect.ts, packages/utils/src/hooks/useWindowSize/useWindowSize.ts
This PR focuses on developer experience and adds JS docs for hooks package
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat(js-docs): Add JS docs for hooks

packages/core/src/components/CheckboxGroup/CheckboxGroup.tsx, packages/core/src/components/CheckboxGroup/types.ts, packages/core/src/components/CheckboxGroup/useKeyboardNavigation.ts
Revert options type
Return object from checkbox group keyboard navigation
-   [ ] Bugfix
-   [ ] Yes
-   [ ] No
=> Refactor Checkbox group keyboard navigation follow up

packages/core/src/components/DateRangePicker/__snapshots__/DateRangePicker.test.tsx.snap, packages/core/src/components/SearchBox/SearchBox.stories.mdx, packages/core/src/components/SearchBox/SearchBox.styled.tsx, packages/core/src/components/SearchBox/SearchBox.tsx, packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap, packages/core/src/components/SearchBox/types.ts, packages/core/src/components/SingleSelect/Options/Options.styled.tsx, packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: searchbox options width issue

packages/core/src/components/DateRangePicker/DateRangePicker.tsx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: close dateRangePicker if both the inputs are out of focus

packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap, packages/core/src/components/SearchBox/styles/options.tsx, packages/core/src/components/SingleSelect/Options/Options.tsx
-   [x] Bugfix
-   [ ] Yes
-   [x] No
=> fix: fix singleselect options same key issue

packages/core/src/components/SearchBox/SearchBox.stories.mdx, packages/core/src/components/SearchBox/SearchBox.stories.tsx, packages/core/src/components/SearchBox/SearchBox.tsx, packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap, packages/core/src/components/SingleSelect/Options/Option/Option.styled.tsx, packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> feat: call onSearch prop on pressing enter key on SearchBox component

packages/core/src/components/MultiSelect/MultiSelect.test.tsx, packages/core/src/components/MultiSelect/Options/Options.tsx
-   [x] Bugfix
-   [ ] Yes
-   [ ] No
=> fix: options id issue of multiselect component

packages/core/src/components/List/List.stories.mdx, packages/core/src/components/Modal/Modal.stories.mdx, packages/core/src/components/Modal/types.ts, packages/core/src/components/Pagination/Pagination.stories.mdx, packages/core/src/components/Popover/Popover.stories.mdx
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> docs: update docs for List, Modal, Pagination and popover component

packages/core/src/components/HelperAndErrorTextTooltip/HelperAndErrorTextTooltip.stories.mdx, packages/core/src/components/HelperAndErrorTextTooltip/types.ts, packages/core/src/components/Input/Input.stories.mdx, packages/core/src/components/Input/types.ts, packages/core/src/components/Label/Label.stories.mdx, packages/core/src/components/Label/types.ts, packages/core/src/components/Link/Link.stories.mdx, packages/core/src/components/Link/types.ts
-   [ ] Bugfix
-   [ ] Yes
-   [x] No
=> docs: update docs of HelperAndErrorTextTooltip, Input, Label & Link component

packages/core/src/components/Drawer/Drawer.test.tsx, packages/core/src/components/Drawer/__snapshots__/Drawer.test.tsx.snap, packages/core/src/components/Modal/Modal.test.tsx, packages/core/src/components/Modal/Modal.tsx, packages/core/src/components/Modal/__snapshots__/Modal.test.tsx.snap, packages/core/src/components/Modal/useScrollState.ts
-   [x] Bugfix
The modal content shadow was not being added for modals that did not have a fixed height (e.g. 420.24px), for modals that had dynamically added or removed children
-   [ ] Yes
-   [x] No
=> fix: fix for shadow issue on modal component

packages/core/src/components/Modal/Modal.tsx, packages/core/src/components/Modal/useScrollState.ts
Changed to Math.Floor so that we round down and get a better experience for modals of unfixed height (e.g. 420.40px)
=> Fix for modal shadow issue

packages/core/src/components/FileInput/FileInput.stories.mdx, packages/core/src/components/SingleSelect/SingleSelect.stories.mdx, packages/core/src/components/SingleSelect/types.ts
=> docs:  update documentation for SingleSelect component

packages/core/src/components/SingleSelect/SingleSelect.test.tsx, packages/core/src/components/SingleSelect/SingleSelect.tsx, packages/core/src/components/SingleSelect/__snapshots__/SingleSelect.test.tsx.snap, packages/core/src/components/SingleSelect/useKeyboardNavigation.tsx
=> fix: single select calling onBlur even on scrollbar click

packages/core/src/components/Modal/Popup/Popup.tsx
Due to stop propagation function in Popup component of Modal, it was preventing event listeners to work inside Modal. In this case, Single select popup doesn't close when clicked outside of single select BUT inside modal.
[ ] Test A
[ ] Test B
(Replace This Text: Please describe any other …
=> fix: single select inside modal not closing

packages/core/src/components/Pagination/Pagination.tsx
Since there was no key prop in, a warning was shown in console for pagination component. That has been fixed
This is a console error that has been fixed
Since there was no key prop a warning was shown in console for pagination component
The warning is not shown anymore
=> fix: add key prop for pagination popup

packages/core/src/components/TextField/TextField.stories.mdx, packages/core/src/components/TextField/getMaskedValue.test.ts, packages/core/src/components/TextField/getMaskedValue.ts
Apply masking on copy pasted text on TextField component.
I have written unit test for this feature.
Masking will not apply on copy pasted text on Textfield
Masking will apply on copy pasted text on Textfield
=> feat: add masking on copy paste in textfield component

packages/loaders/src/Loaders.stories.mdx
=> AM|content changes-loaders

packages/icons/src/Icons.stories.mdx
=> AM|content changes-icons

packages/layout/src/components/Header/Header.stories.mdx
=> Layoutheader

docs/Typography/Typography.stories.mdx
=> Typography

packages/utils/src/components/InjectClassName/InjectClassName.stories.mdx
=> AM|content changes- components

packages/utils/src/types/GetComponentProps/GetComponentProps.stories.mdx, packages/utils/src/types/HTMLProps/HTMLProps.stories.mdx, packages/utils/src/types/WithStyle/WithStyle.stories.mdx
=> AM|content changes-types

packages/forms/src/components/Fields/Fields.components.tsx
Fix file input value where the input placeholder was not being updated/cleared, after opening of `select a file` HTML modal and clicking cancel.
[ ] Test A
[ ] Test B
The stale file placeholder is shown 
Placeholder value is updated with correct value
=> fix(core): file input placeholder value

packages/core/src/components/Toggle/Toggle.stories.mdx, packages/core/src/components/Toggle/Toggle.styled.tsx, packages/core/src/components/Toggle/Toggle.test.tsx, packages/core/src/components/Toggle/Toggle.tsx, packages/core/src/components/Toggle/__snapshots__/Toggle.test.tsx.snap, packages/core/src/components/Toggle/types.ts, packages/theme/src/core/toggle/index.ts, packages/theme/src/core/toggle/types.ts
ISSUES CLOSED: #579
[ ] Test A
[ ] Test B …
=> feat: add icon support in toggle button

packages/core/src/components/Table/Body/Cell/Cell.tsx, packages/core/src/components/Table/Table.test.tsx, packages/core/src/components/Table/__snapshots__/Table.test.tsx.snap
fixes table component security issue. If we pass table cell data as an executable HTML tag, the Cell component accepts it as inner Html and executes it making it vulnerable to XSS attack.
[ ] Test A
[ ] Test B
If we pass table cell data as an executable HTML tag, the Cell component accepts it as inner Html and executes it.
If we pass table cell data as an executable HTML tag, the Cell component will accept it as plain text. …
=> fix(core): fix table security issue

packages/core/src/components/SingleSelect/SingleSelect.tsx
Resolve single select field issue
[ ] Test A
[ ] Test B
When clicked on single select field and then clicked outside, validation error message is shown
When clicked on single select field and then clicked outside, no validation error message is shown
(Replace This …
=> fix: Resolve single select field validation issue

packages/markdown/src/components/MarkdownContent/MarkdownContent.stories.mdx
=> AM|content changes-markdown

packages/utils/src/style/breakpoints/breakpoints.stories.mdx, packages/utils/src/style/centerAligned/centerAligned.stories.mdx, packages/utils/src/style/getFontStyle/getFontStyle.stories.mdx, packages/utils/src/style/media/media.stories.mdx
=> AM|content change-style

packages/utils/src/helpers/cookieStorage/cookieStorage.stories.mdx, packages/utils/src/helpers/debounce/debounce.stories.mdx, packages/utils/src/helpers/localStorage/localStorage.stories.mdx, packages/utils/src/helpers/sessionStorage/sessionStorage.stories.mdx, packages/utils/src/helpers/updateNestedValue/updateNestedValue.stories.mdx
=> AM|content changes-helpers

packages/core/src/components/Breadcrumb/Back/Back.tsx, packages/core/src/components/Breadcrumb/Back/types.ts, packages/core/src/components/Breadcrumb/Item/Item.styled.tsx, packages/core/src/components/Breadcrumb/__snapshots__/Breadcrumb.test.tsx.snap
- Add as prop in Breadcrumb Back button component so that we can render the component as any other component like render it as Link component
- Also add text decoration none because if we render it as Link then tag styles add underline.
[ ] Test A
[ ] Test B
Right now we cannot render it as any other component
We can now render it as any other component …
=> feat: add as prop in Breadcrumb Back button component

packages/forms/src/components/Form/Form.tsx, packages/forms/src/components/Form/types.ts
Make form component generic so that its `intialState, onSubmit, fieldSchema & onChange` can all take same type.
[ ] Test A
[ ] Test B
=> feat: make form component generic

package.json, packages/utils/package.json, packages/utils/src/hooks/useSWRAxios/types.ts, packages/utils/src/hooks/useSWRAxios/useSWRAxios.test.tsx, packages/utils/src/hooks/useSWRAxios/useSWRAxios.ts, test-utils.tsx, yarn.lock
BREAKING CHANGE:
upgrade to swr2.0 which has breaking changes
Upgrade to SWR 2.0 which has lot of new features. Checkout the complete blog over [here](https://swr.vercel.app/blog/swr-v2)
[ ] Test A
[ ] Test B
The latest version of SWR has some braking changes.
=> feat: upgrade swr to latest version

packages/utils/src/hooks/useSWRAxios/types.ts, packages/utils/src/hooks/useSWRAxios/useSWRAxios.test.tsx, packages/utils/src/hooks/useSWRAxios/useSWRAxios.ts
It includes below changes:
1. Update the `Data` return type when we pass `fallbackData`
2. The `response` will be updated when the error occurs with error response.
3. The `error` will now have the error data instead of the whole axios error response.
[ ] Test A
[ ] Test B
**Note:** (Replace This Text: If this PR contains a breaking change please describe the impact and migration path for existing …
=> feat: update useSWRAxios return type

packages/core/src/components/SearchBox/SearchBox.tsx, packages/core/src/components/SearchBox/__snapshots__/SearchBox.test.tsx.snap
ISSUES CLOSED: #730
- x ] Code style update (formatting, local variables)
[ ] Test A
[ ] Test B
=> fix(core): searchBox: clear/close icon not hiding when we manually clear the state value
